/**
 * POST /api/v1/auth/oauth/start
 *
 * Initiates a server-side OAuth flow for CLI callers. The CLI has no session
 * before auth — it can't authenticate against a protected endpoint to start
 * the login flow. This endpoint is therefore INTENTIONALLY unauthenticated.
 *
 * Flow:
 *   1. CLI POSTs here with { provider, redirect_to }.
 *   2. Server calls Supabase `signInWithOAuth` (PKCE) and gets back an
 *      authorization URL.
 *   3. Server returns { authorization_url, state } to the CLI.
 *   4. CLI opens the authorization URL in the user's browser.
 *   5. After the user authenticates, the OAuth provider redirects to
 *      `redirect_to` (typically a localhost callback server or a deep-link
 *      into the mobile app).
 *
 * State design:
 *   WHY return `state` to the CLI: in a standard browser flow, Supabase
 *   manages the PKCE code_verifier + state via a cookie on the same origin.
 *   For a CLI-initiated flow the "browser" and the "app" are decoupled —
 *   the CLI spawns a local HTTP callback server, and there is no shared cookie
 *   jar between the server and the CLI. We therefore extract the `state`
 *   parameter from the authorization URL (Supabase inserts it as a query
 *   param) and return it to the CLI so the CLI can validate it on the callback
 *   request from the browser (CSRF defense per RFC 6749 §10.12).
 *
 * Security:
 *   - IP-based rate limit (10/min) — no API key available yet, so rate limiting
 *     is per-IP. Aggressive enough to block state-flooding but generous for
 *     humans retrying a failed login.
 *   - Provider enum is CLOSED — only known providers accepted (OWASP A03).
 *   - redirect_to origin is validated against an allowlist (OWASP A01 —
 *     open-redirect defense). The error message does NOT echo the rejected URL.
 *   - PKCE code_verifier is generated by Supabase — never rolled manually.
 *   - No idempotency middleware: each initiation MUST create fresh PKCE state.
 *
 * @auth UNAUTHENTICATED — caller has no session or API key yet.
 *       This is a Category C endpoint (pre-auth).
 *
 * @rateLimit 10 requests per minute per IP
 *
 * @body {
 *   provider: 'github' | 'google',
 *   redirect_to: string  // Must be a URL; origin must be in allowlist
 * }
 *
 * @returns 200 {
 *   authorization_url: string,  // Open this in the user's browser
 *   state: string               // CLI stores and validates on callback (RFC 6749 §10.12)
 * }
 *
 * @error 400 { error: 'VALIDATION_ERROR', message: string }  — Zod failure
 * @error 400 { error: 'REDIRECT_NOT_ALLOWED' }               — origin not in allowlist
 * @error 429 { error: 'RATE_LIMITED', retryAfter: number }   — IP cap exceeded
 * @error 500 { error: 'INTERNAL_ERROR' }                     — Supabase failure (Sentry)
 *
 * @security OWASP A01:2021 (Broken Access Control — open-redirect defense on redirect_to)
 * @security OWASP A03:2021 (Injection / Mass Assignment — Zod .strict() + closed provider enum)
 * @security OWASP A07:2021 (Identification and Authentication Failures — bridges INTO auth flow)
 * @security GDPR Art 6 (Lawful basis — no processing before consent via OAuth)
 * @security SOC 2 CC6.1 (Logical Access Controls — state token CSRF guard)
 *
 * @module api/v1/auth/oauth/start
 */

import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import * as Sentry from '@sentry/nextjs';
import { createAdminClient } from '@/lib/supabase/server';
import { rateLimit, rateLimitResponse } from '@/lib/rateLimit';

// ============================================================================
// Constants
// ============================================================================

/**
 * Rate limit: 10 requests per minute per IP.
 *
 * WHY 10/min: A human user needs at most 1-2 OAuth initiations per retry
 * cycle. 10/min is generous for retries (e.g. port conflict on callback
 * server) but aggressive enough to block automated state-flooding attacks,
 * which would force Supabase to generate thousands of PKCE code_verifiers
 * (server resource consumption).
 */
export const OAUTH_START_RATE_LIMIT = { windowMs: 60_000, maxRequests: 10 };

/**
 * Maximum length of the redirect_to URL in bytes.
 *
 * WHY 2048: Standard browser URL length limit. Longer URLs are almost
 * certainly injection attempts or misconfigured clients; reject them early
 * to prevent downstream surprises.
 */
export const MAX_REDIRECT_URL_LENGTH = 2048;

/**
 * Allowlist of origins that redirect_to may point to.
 *
 * WHY an allowlist: OWASP A01:2021 — without this, an attacker could call
 * this endpoint with `redirect_to: "https://attacker.com/steal-code"`,
 * craft a phishing link containing a real Supabase authorization URL that
 * redirects to their domain after the user authenticates, and steal the
 * authorization code. The authorization code alone is useless without
 * the PKCE code_verifier (Supabase PKCE mitigates the worst case), but
 * a naive exchange can still leak session data.
 *
 * Patterns:
 *   - `localhost` / `127.0.0.1` — CLI callback server
 *   - `styrbyapp.com` — production web app deep-link
 *   - `*.vercel.app` — Vercel preview deployments
 *   - `exp://` scheme — Expo Go deep-link during development
 */
export const OAUTH_ALLOWED_REDIRECT_ORIGINS: Array<string | RegExp> = [
  // CLI local callback server
  /^http:\/\/localhost(:\d+)?$/,
  /^http:\/\/127\.0\.0\.1(:\d+)?$/,
  // Production domain
  'https://styrbyapp.com',
  // Vercel preview deployments
  /^https:\/\/[a-zA-Z0-9-]+-vetsecitpro\.vercel\.app$/,
  /^https:\/\/styrby-[a-zA-Z0-9-]+\.vercel\.app$/,
  // Expo Go / mobile dev (exp:// deep-link)
  /^exp:\/\//,
];

// ============================================================================
// Zod Schema
// ============================================================================

/**
 * Request body schema for POST /api/v1/auth/oauth/start.
 *
 * WHY .strict(): rejects any field not listed here (mass-assignment defense,
 * OWASP A03:2021). A caller injecting `state`, `code_challenge`, or any
 * Supabase-internal param won't be able to influence the server's PKCE flow.
 *
 * WHY provider enum: only accept providers the CLI has verified OAuth app
 * configurations for. The CLI's browser-auth.ts currently uses 'github'
 * (OAuthProvider type = 'github'). We add 'google' per the Strategy C spec.
 * Adding more later requires explicit code review of the Supabase OAuth config.
 */
const OAuthStartSchema = z
  .object({
    /** OAuth provider to authenticate with. Must be a pre-configured Supabase provider. */
    provider: z.enum(['github', 'google']),

    /**
     * URL the OAuth provider should redirect the user to after authentication.
     * Must be a valid URL with an origin in OAUTH_ALLOWED_REDIRECT_ORIGINS.
     * Typically a localhost callback server (CLI) or an app deep-link (mobile).
     */
    redirect_to: z.string().url().max(MAX_REDIRECT_URL_LENGTH),
  })
  .strict();

type OAuthStartBody = z.infer<typeof OAuthStartSchema>;

// ============================================================================
// Helpers
// ============================================================================

/**
 * Validates that a redirect_to URL's origin is in the allowlist.
 *
 * WHY a dedicated function (not inline): this is a security-critical check.
 * Isolating it makes unit testing trivial and keeps the handler readable.
 *
 * @param url - The parsed URL to check.
 * @returns true if the origin is allowed, false otherwise.
 */
export function isAllowedRedirectOrigin(url: URL): boolean {
  const origin = url.origin; // e.g. "http://localhost:3333"
  const href = url.href;     // for exp:// which has no "origin"

  for (const allowed of OAUTH_ALLOWED_REDIRECT_ORIGINS) {
    if (typeof allowed === 'string') {
      if (origin === allowed) return true;
    } else {
      // RegExp — test against origin first, then full href for non-http schemes
      if (allowed.test(origin) || allowed.test(href)) return true;
    }
  }
  return false;
}

/**
 * Extracts the `state` parameter from a Supabase authorization URL.
 *
 * WHY extract from URL (not from Supabase response): Supabase's
 * `signInWithOAuth` return value has `data.url` but does NOT expose
 * the state separately. We parse it from the URL query string.
 * The state is unguessable (Supabase generates it internally); we only
 * need to pluck and forward it so the CLI can validate CSRF on callback.
 *
 * @param authUrl - The full authorization URL from Supabase.
 * @returns The state string, or undefined if not present.
 */
export function extractStateFromAuthUrl(authUrl: string): string | undefined {
  try {
    const url = new URL(authUrl);
    return url.searchParams.get('state') ?? undefined;
  } catch {
    return undefined;
  }
}

// ============================================================================
// Handler
// ============================================================================

/**
 * POST /api/v1/auth/oauth/start
 *
 * Unauthenticated OAuth initiation. See module-level JSDoc for full spec.
 *
 * @param request - The incoming NextRequest from the CLI.
 * @returns 200 { authorization_url, state } on success.
 */
export async function POST(request: NextRequest) {
  // ── 1. IP-based rate limit ─────────────────────────────────────────────────
  // WHY: No API key is available yet (caller is pre-auth), so we rate-limit
  // per IP. The 'oauth-start' prefix isolates this bucket from other endpoints.
  const rateLimitResult = await rateLimit(request, OAUTH_START_RATE_LIMIT, 'oauth-start');
  if (!rateLimitResult.allowed) {
    return rateLimitResponse(rateLimitResult.retryAfter ?? 60);
  }

  // ── 2. Parse and validate request body ────────────────────────────────────
  let rawBody: unknown;
  try {
    rawBody = await request.json();
  } catch {
    return NextResponse.json(
      { error: 'VALIDATION_ERROR', message: 'Request body must be valid JSON.' },
      { status: 400 }
    );
  }

  const parsed = OAuthStartSchema.safeParse(rawBody);
  if (!parsed.success) {
    return NextResponse.json(
      {
        error: 'VALIDATION_ERROR',
        message: parsed.error.issues[0]?.message ?? 'Invalid request body.',
      },
      { status: 400 }
    );
  }

  const body: OAuthStartBody = parsed.data;

  // ── 3. Allowlist check on redirect_to (OWASP A01:2021 — open-redirect) ────
  // WHY: Without this check, an attacker could supply redirect_to pointing
  // to their own domain and use this endpoint as an open-redirect oracle,
  // potentially phishing OAuth codes from unsuspecting users.
  let redirectUrl: URL;
  try {
    redirectUrl = new URL(body.redirect_to);
  } catch {
    // Should not reach here (Zod's .url() already validates); belt-and-suspenders.
    return NextResponse.json(
      { error: 'VALIDATION_ERROR', message: 'redirect_to is not a valid URL.' },
      { status: 400 }
    );
  }

  if (!isAllowedRedirectOrigin(redirectUrl)) {
    // WHY: Do NOT echo the rejected URL in the error response. Echoing the URL
    // would create an information-leakage vector (e.g. reflected XSS in apps
    // that render this message) and confirm to an attacker which origins are
    // blocked vs. not. Generic message only.
    return NextResponse.json(
      { error: 'REDIRECT_NOT_ALLOWED' },
      { status: 400 }
    );
  }

  // ── 4. Call Supabase signInWithOAuth (PKCE) ────────────────────────────────
  // WHY admin client (not user-scoped): the caller has no session yet.
  // createAdminClient() is called per-request (not module-level) so that each
  // invocation gets a fresh client instance — avoids cross-request state leakage
  // in serverless environments where the module may be reused across requests.
  const supabase = createAdminClient();

  let authUrl: string;
  try {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: body.provider,
      options: {
        redirectTo: body.redirect_to,
        // WHY skipBrowserRedirect: true — this is a server-side call. We only
        // want the authorization URL; we are NOT redirecting from a browser
        // context. Without this flag, the Supabase client may attempt a redirect
        // that has no effect in a server context but may emit warnings.
        skipBrowserRedirect: true,
        queryParams: {
          // WHY flowType pkce: PKCE is mandatory for public clients (CLI / mobile).
          // The code_verifier never leaves the server's Supabase client; only the
          // code_challenge is sent to the OAuth provider.
          // Note: flowType is set via createAdminClient's auth config if applicable;
          // queryParams can carry additional OAuth params.
        },
      },
    });

    if (error || !data?.url) {
      const message = error?.message ?? 'No authorization URL returned';
      Sentry.captureException(new Error(`signInWithOAuth failed: ${message}`), {
        tags: { endpoint: '/api/v1/auth/oauth/start', provider: body.provider },
      });
      return NextResponse.json({ error: 'INTERNAL_ERROR' }, { status: 500 });
    }

    authUrl = data.url;
  } catch (err) {
    Sentry.captureException(err, {
      tags: { endpoint: '/api/v1/auth/oauth/start', provider: body.provider },
    });
    return NextResponse.json({ error: 'INTERNAL_ERROR' }, { status: 500 });
  }

  // ── 5. Extract state from authorization URL ────────────────────────────────
  // WHY: Supabase embeds the CSRF state token as a query parameter in the
  // authorization URL. We extract and return it to the CLI so the CLI can
  // validate it when the OAuth provider redirects back (RFC 6749 §10.12).
  const state = extractStateFromAuthUrl(authUrl);

  // ── 6. Return 200 with authorization URL and state ─────────────────────────
  // WHY 200 (not 201): this endpoint initiates a flow, it does not CREATE a
  // persistent resource. 201 implies a resource was created and returns a
  // Location header; that semantic doesn't apply here.
  return NextResponse.json(
    {
      authorization_url: authUrl,
      state: state ?? null,
    },
    { status: 200 }
  );
}
