/**
 * Unified API error shape (Phase 0.10).
 *
 * Every Styrby HTTP/RPC API surface — web routes, edge functions, mobile
 * client wrappers — returns errors in this shape. Centralising the shape
 * eliminates the prior inconsistency where some routes returned
 * `{ error: 'BAD_REQUEST' }`, others `{ message: 'invalid' }`, and others
 * a bare string. Consistent error shapes are an OWASP ASVS V7.4 control
 * (the application provides predictable error responses) and let the
 * mobile client write a single decoder instead of one per route.
 *
 * @module api/errors
 */

/**
 * The canonical error envelope returned by every API surface on failure.
 *
 * @property code - Stable machine-readable identifier (UPPER_SNAKE_CASE).
 *   Use this for switch/case in clients; never branch on `message`.
 * @property message - Human-readable, user-safe description. May be shown
 *   in mobile UI or web toasts.
 * @property details - Optional structured context (e.g., field names that
 *   failed validation, retry-after seconds, current/limit values).
 *   MUST NOT contain PII, secrets, stack traces, or SQL. Audited via the
 *   `assertNoSecretsInDetails()` helper.
 * @property requestId - Optional correlation id; surfaced from the
 *   incoming request id header / generated by the edge layer.
 * @property timestamp - ISO 8601 timestamp of error creation. Set by
 *   `apiError()` so callers cannot forget it.
 */
export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
  requestId?: string;
  timestamp: string;
}

/**
 * A catalog of error codes used across the system. Adding a new code? Add
 * it here so the type system can flag typos at call sites.
 *
 * WHY a const tuple (not an enum): const enums break tree-shaking under
 * Next.js's swc compiler, and string enums add runtime objects we don't
 * need. A `as const` array gives us the same exhaustiveness with zero
 * runtime cost.
 */
export const API_ERROR_CODES = [
  // Auth / authorization
  'UNAUTHORIZED',
  'FORBIDDEN',
  'INVALID_TOKEN',
  // Input validation
  'BAD_REQUEST',
  'VALIDATION_FAILED',
  'INVALID_AGENT_TYPE',
  // Tier / billing
  'TIER_LIMIT_EXCEEDED',
  'PAYMENT_REQUIRED',
  'SUBSCRIPTION_EXPIRED',
  // Rate limiting
  'RATE_LIMITED',
  // Resource state
  'NOT_FOUND',
  'CONFLICT',
  'GONE',
  // Server / dependencies
  'INTERNAL_ERROR',
  'UPSTREAM_ERROR',
  'SUPABASE_ERROR',
  'POLAR_ERROR',
] as const;

/** Type-safe union of all known error codes. */
export type ApiErrorCode = (typeof API_ERROR_CODES)[number];

/**
 * Build an {@link ApiError} with sensible defaults. Always prefer this
 * helper over hand-constructed object literals so the timestamp is always
 * set and the audit checks below run uniformly.
 *
 * @param code - One of {@link API_ERROR_CODES}, or any string for
 *   gradual migration. Prefer the typed values.
 * @param message - Human-readable description.
 * @param details - Optional structured context (no secrets).
 * @param requestId - Optional correlation id.
 * @returns A fully-formed {@link ApiError}.
 *
 * @example
 * ```ts
 * return Response.json(
 *   apiError('TIER_LIMIT_EXCEEDED', 'Free tier allows 5 sessions/day', {
 *     limit: 5, current: 5, tier: 'free',
 *   }),
 *   { status: 403 }
 * );
 * ```
 */
export function apiError(
  code: ApiErrorCode | string,
  message: string,
  details?: Record<string, unknown>,
  requestId?: string,
): ApiError {
  if (details) assertNoSecretsInDetails(details);
  const error: ApiError = {
    code,
    message,
    timestamp: new Date().toISOString(),
  };
  if (details) error.details = details;
  if (requestId) error.requestId = requestId;
  return error;
}

/**
 * Audit guard (OWASP ASVS V7.1 / V8.3): scans the `details` object for
 * common secret-shaped keys and throws in development. Production behavior
 * is to silently strip the key — we never want to leak a secret, but we
 * also do not want a runtime crash to expose a different bug class.
 *
 * @param details - The structured context being attached to an ApiError.
 * @throws Error in development if a secret-shaped key is present.
 */
export function assertNoSecretsInDetails(details: Record<string, unknown>): void {
  // Common secret-shaped keys. Lowercased substrings are matched.
  const FORBIDDEN = [
    'password',
    'secret',
    'token',
    'apikey',
    'api_key',
    'authorization',
    'cookie',
    'service_role',
    'private_key',
  ];
  for (const key of Object.keys(details)) {
    const k = key.toLowerCase();
    if (FORBIDDEN.some((needle) => k.includes(needle))) {
      // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
      delete details[key];
      if (process.env.NODE_ENV === 'development') {
        throw new Error(
          `apiError(): refused to attach secret-shaped key "${key}" to error details`,
        );
      }
    }
  }
}

/**
 * Type guard for {@link ApiError}. Useful in mobile/web error handlers that
 * receive `unknown` (e.g., from `await response.json()`).
 *
 * @param value - Any value, typically a parsed JSON response body.
 * @returns `true` when `value` matches the {@link ApiError} contract.
 */
export function isApiError(value: unknown): value is ApiError {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.code === 'string' &&
    typeof v.message === 'string' &&
    typeof v.timestamp === 'string'
  );
}
