/**
 * CloudTaskSubmitSheet
 *
 * Bottom-sheet modal for dispatching a new cloud agent task from the phone.
 * Power-tier users open this from the Cloud Tasks screen's "+" FAB.
 *
 * UX choices made for this sheet (see PR-2 of #97 for the design discussion):
 * - "Choose from a recent session" lets the user link the task to an existing
 *   project context with one tap, avoiding free-form repo path entry on a
 *   phone keyboard. The selected session's projectPath + gitBranch are
 *   copied into the task's metadata.
 * - Agent picker pre-selects 'claude' (the default agent across the app) and
 *   lets the user override. Only the 11 agents the cloud_tasks.agent_type
 *   CHECK constraint accepts are surfaced (see SUBMITTABLE_AGENTS).
 * - Standalone (no session link) is allowed — useful for one-shot prompts
 *   like "list my open Linear issues" that aren't tied to a repo.
 *
 * Submission flow:
 * 1. User fills in prompt, optionally picks agent + session
 * 2. submitCloudTask() inserts a queued row → Realtime delivers the new row
 *    to <CloudTasks/> which prepends it to the list
 * 3. The relay infrastructure picks up the queued task and starts execution
 * 4. Status updates flow back via Realtime; the user sees them live
 */

import { useEffect, useMemo, useState } from 'react';
import {
  View,
  Text,
  Modal,
  Pressable,
  ScrollView,
  TextInput,
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '../../lib/supabase';
import { submitCloudTask, SUBMITTABLE_AGENTS } from '../../services/cloud-tasks';
import type { AgentType, CloudTask } from 'styrby-shared';

/**
 * A condensed view of a session for the picker. We only need enough to render
 * the row and to populate the new task's metadata + session_id link.
 */
export interface RecentSessionOption {
  /** sessions.id — used as cloud_tasks.session_id when linked. */
  id: string;
  /** sessions.title (auto-generated by the agent) — null if untitled. */
  title: string | null;
  /** sessions.project_path — copied to cloud_tasks.metadata.projectPath. */
  projectPath: string | null;
  /** sessions.git_branch — copied to cloud_tasks.metadata.gitBranch. */
  gitBranch: string | null;
  /** sessions.agent_type — used to pre-select the picker when linking. */
  agentType: AgentType;
  /** sessions.started_at — formatted relatively in the picker row. */
  startedAt: string;
}

/**
 * Props for the CloudTaskSubmitSheet component.
 */
export interface CloudTaskSubmitSheetProps {
  /**
   * Whether the modal is currently visible.
   */
  visible: boolean;

  /**
   * Called when the user dismisses the sheet without submitting.
   */
  onDismiss: () => void;

  /**
   * Called after a successful submission with the newly-inserted task.
   * Allows the parent screen to optimistically prepend the new task to its
   * list (Realtime will deliver the same row shortly after, deduped by id).
   *
   * @param task - The CloudTask returned by submitCloudTask
   */
  onSubmitted: (task: CloudTask) => void;
}

/**
 * Display label for each agent in the picker.
 *
 * WHY a separate label table: AgentType is lowercase/short; users expect
 * proper-case names like "Claude Code" not "claude". Mirrors the dashboard
 * AGENTS array's `name` field for the three primary agents and follows
 * the same "<Brand> <Capability>" pattern for the rest.
 */
const AGENT_LABELS: Record<AgentType, string> = {
  claude: 'Claude Code',
  codex: 'Codex CLI',
  gemini: 'Gemini CLI',
  opencode: 'OpenCode',
  aider: 'Aider',
  goose: 'Goose',
  amp: 'Amp',
  crush: 'Crush',
  kilo: 'Kilo',
  kiro: 'Kiro',
  droid: 'Droid',
};

/**
 * Renders a relative-time string ("2h ago", "yesterday") for the recent
 * sessions picker.
 *
 * @param iso - ISO 8601 timestamp string
 */
function formatRelative(iso: string): string {
  const diffMs = Date.now() - new Date(iso).getTime();
  const diffMin = Math.floor(diffMs / 60_000);
  const diffHr = Math.floor(diffMin / 60);
  if (diffMin < 1) return 'just now';
  if (diffMin < 60) return `${diffMin}m ago`;
  if (diffHr < 24) return `${diffHr}h ago`;
  return `${Math.floor(diffHr / 24)}d ago`;
}

/**
 * Bottom-sheet UI for dispatching a new cloud task.
 *
 * @param props - CloudTaskSubmitSheetProps
 * @returns React element
 */
export function CloudTaskSubmitSheet({
  visible,
  onDismiss,
  onSubmitted,
}: CloudTaskSubmitSheetProps) {
  // Form state
  const [agent, setAgent] = useState<AgentType>('claude');
  const [prompt, setPrompt] = useState('');
  const [linkedSession, setLinkedSession] = useState<RecentSessionOption | null>(null);

  // Recent sessions picker state
  const [sessions, setSessions] = useState<RecentSessionOption[]>([]);
  const [sessionsLoading, setSessionsLoading] = useState(false);
  const [sessionsError, setSessionsError] = useState<string | null>(null);

  // Submission state
  const [isSubmitting, setIsSubmitting] = useState(false);

  // --------------------------------------------------------------------------
  // Reset form on every open
  // --------------------------------------------------------------------------

  useEffect(() => {
    if (visible) {
      setAgent('claude');
      setPrompt('');
      setLinkedSession(null);
      setIsSubmitting(false);
      setSessionsError(null);
    }
  }, [visible]);

  // --------------------------------------------------------------------------
  // Load recent sessions for the picker (only when sheet opens)
  // --------------------------------------------------------------------------

  useEffect(() => {
    if (!visible) return;
    let cancelled = false;
    setSessionsLoading(true);
    setSessionsError(null);

    void (async () => {
      // WHY explicit user scope: on a team, sessions RLS permits reading
      // teammates' rows. The recent-sessions picker is a PERSONAL convenience
      // list, so without .eq('user_id', ...) it leaked other members' session
      // titles / project_path / git_branch. Scope to the authed user explicitly
      // (defence in depth — do not rely on RLS alone for this UI affordance).
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (cancelled) return;
      if (!user) {
        setSessions([]);
        setSessionsLoading(false);
        return;
      }

      const { data, error } = await supabase
        .from('sessions')
        .select('id, title, project_path, git_branch, agent_type, started_at')
        .eq('user_id', user.id)
        .order('started_at', { ascending: false })
        .limit(10);

      if (cancelled) return;
      if (error) {
        setSessionsError(error.message);
        setSessions([]);
      } else if (data) {
        setSessions(
          data.map((row): RecentSessionOption => ({
            id: row.id as string,
            title: (row.title as string | null) ?? null,
            projectPath: (row.project_path as string | null) ?? null,
            gitBranch: (row.git_branch as string | null) ?? null,
            agentType: row.agent_type as AgentType,
            startedAt: row.started_at as string,
          })),
        );
      }
      setSessionsLoading(false);
    })();

    return () => { cancelled = true; };
  }, [visible]);

  // --------------------------------------------------------------------------
  // Derived state
  // --------------------------------------------------------------------------

  const canSubmit = useMemo(
    () => prompt.trim().length > 0 && !isSubmitting,
    [prompt, isSubmitting],
  );

  // --------------------------------------------------------------------------
  // Handlers
  // --------------------------------------------------------------------------

  /**
   * Picks a session: copies its agent + path/branch into the form so the
   * resulting task is contextual to that session's repo.
   */
  function handleSessionPick(session: RecentSessionOption) {
    setLinkedSession(session);
    // Pre-select the session's agent — most users want to keep the same one,
    // but they can override with the picker chips after.
    setAgent(session.agentType);
  }

  /**
   * Submits the form. On success: notifies parent, then dismisses.
   * On failure: surfaces the error in an Alert and stays open so the user
   * can fix and retry without losing what they typed.
   */
  async function handleSubmit() {
    if (!canSubmit) return;
    setIsSubmitting(true);
    try {
      const task = await submitCloudTask({
        prompt,
        agentType: agent,
        sessionId: linkedSession?.id ?? null,
        metadata: linkedSession
          ? {
              ...(linkedSession.projectPath ? { projectPath: linkedSession.projectPath } : {}),
              ...(linkedSession.gitBranch ? { gitBranch: linkedSession.gitBranch } : {}),
            }
          : undefined,
      });
      onSubmitted(task);
      onDismiss();
    } catch (e) {
      Alert.alert(
        'Could not submit task',
        e instanceof Error ? e.message : 'Unknown error',
      );
    } finally {
      setIsSubmitting(false);
    }
  }

  // --------------------------------------------------------------------------
  // Render
  // --------------------------------------------------------------------------

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      onRequestClose={onDismiss}
      accessibilityViewIsModal
    >
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={{ flex: 1 }}
      >
        <View
          style={{
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.7)',
            justifyContent: 'flex-end',
          }}
        >
          <View
            style={{
              backgroundColor: '#18181b',
              borderTopLeftRadius: 20,
              borderTopRightRadius: 20,
              maxHeight: '90%',
            }}
          >
            {/* Header */}
            <View
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                paddingHorizontal: 16,
                paddingVertical: 14,
                borderBottomWidth: 1,
                borderBottomColor: '#27272a',
              }}
            >
              <Text style={{ color: 'white', fontSize: 17, fontWeight: '700', flex: 1 }}>
                New Cloud Task
              </Text>
              <Pressable
                onPress={onDismiss}
                style={{ padding: 4 }}
                accessibilityRole="button"
                accessibilityLabel="Close new task sheet"
              >
                <Ionicons name="close" size={22} color="#71717a" />
              </Pressable>
            </View>

            <ScrollView
              keyboardShouldPersistTaps="handled"
              contentContainerStyle={{ padding: 16, paddingBottom: 24 }}
            >
              {/* Agent picker */}
              <Text
                style={{
                  color: '#a1a1aa',
                  fontSize: 12,
                  fontWeight: '600',
                  textTransform: 'uppercase',
                  marginBottom: 8,
                }}
              >
                Agent
              </Text>
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                style={{ marginBottom: 18 }}
                accessibilityRole="radiogroup"
                accessibilityLabel="Choose an agent for this task"
              >
                {SUBMITTABLE_AGENTS.map((a) => {
                  const isSelected = a === agent;
                  return (
                    <Pressable
                      key={a}
                      onPress={() => setAgent(a)}
                      style={{
                        backgroundColor: isSelected ? '#f97316' : '#27272a',
                        paddingHorizontal: 14,
                        paddingVertical: 8,
                        borderRadius: 999,
                        marginRight: 8,
                      }}
                      accessibilityRole="radio"
                      accessibilityState={{ selected: isSelected }}
                      accessibilityLabel={`${AGENT_LABELS[a]} agent${isSelected ? ', selected' : ''}`}
                    >
                      <Text
                        style={{
                          color: isSelected ? 'white' : '#d4d4d8',
                          fontSize: 13,
                          fontWeight: '600',
                        }}
                      >
                        {AGENT_LABELS[a]}
                      </Text>
                    </Pressable>
                  );
                })}
              </ScrollView>

              {/* Recent sessions picker */}
              <Text
                style={{
                  color: '#a1a1aa',
                  fontSize: 12,
                  fontWeight: '600',
                  textTransform: 'uppercase',
                  marginBottom: 8,
                }}
              >
                Link to a recent session (optional)
              </Text>
              {sessionsLoading ? (
                <View style={{ padding: 12, alignItems: 'center' }}>
                  <ActivityIndicator size="small" color="#71717a" />
                </View>
              ) : sessionsError ? (
                <Text style={{ color: '#fca5a5', fontSize: 13, marginBottom: 18 }}>
                  Could not load sessions: {sessionsError}
                </Text>
              ) : sessions.length === 0 ? (
                <Text style={{ color: '#71717a', fontSize: 13, marginBottom: 18 }}>
                  No recent sessions to link.
                </Text>
              ) : (
                <View style={{ marginBottom: 18 }}>
                  {/* "None" option */}
                  <Pressable
                    onPress={() => setLinkedSession(null)}
                    style={{
                      flexDirection: 'row',
                      alignItems: 'center',
                      paddingVertical: 10,
                      paddingHorizontal: 12,
                      borderRadius: 10,
                      backgroundColor: linkedSession === null ? '#27272a' : 'transparent',
                      marginBottom: 4,
                    }}
                    accessibilityRole="radio"
                    accessibilityState={{ selected: linkedSession === null }}
                    accessibilityLabel="No session link, standalone task"
                  >
                    <Ionicons
                      name={linkedSession === null ? 'radio-button-on' : 'radio-button-off'}
                      size={18}
                      color={linkedSession === null ? '#f97316' : '#52525b'}
                    />
                    <Text style={{ color: '#d4d4d8', fontSize: 14, marginLeft: 10 }}>
                      None (standalone task)
                    </Text>
                  </Pressable>
                  {sessions.map((s) => {
                    const isSelected = linkedSession?.id === s.id;
                    return (
                      <Pressable
                        key={s.id}
                        onPress={() => handleSessionPick(s)}
                        style={{
                          flexDirection: 'row',
                          alignItems: 'flex-start',
                          paddingVertical: 10,
                          paddingHorizontal: 12,
                          borderRadius: 10,
                          backgroundColor: isSelected ? '#27272a' : 'transparent',
                          marginBottom: 4,
                        }}
                        accessibilityRole="radio"
                        accessibilityState={{ selected: isSelected }}
                        accessibilityLabel={`Link to session: ${s.title ?? 'Untitled'}, ${formatRelative(s.startedAt)}`}
                      >
                        <Ionicons
                          name={isSelected ? 'radio-button-on' : 'radio-button-off'}
                          size={18}
                          color={isSelected ? '#f97316' : '#52525b'}
                          style={{ marginTop: 2 }}
                        />
                        <View style={{ marginLeft: 10, flex: 1 }}>
                          <Text
                            style={{ color: '#e4e4e7', fontSize: 14, fontWeight: '500' }}
                            numberOfLines={1}
                          >
                            {s.title ?? 'Untitled session'}
                          </Text>
                          <View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 2 }}>
                            <Text style={{ color: '#71717a', fontSize: 12 }}>
                              {AGENT_LABELS[s.agentType]} · {formatRelative(s.startedAt)}
                            </Text>
                          </View>
                          {s.gitBranch && (
                            <View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 2 }}>
                              <Ionicons name="git-branch-outline" size={11} color="#71717a" />
                              <Text style={{ color: '#71717a', fontSize: 11, marginLeft: 4 }}>
                                {s.gitBranch}
                              </Text>
                            </View>
                          )}
                        </View>
                      </Pressable>
                    );
                  })}
                </View>
              )}

              {/* Prompt */}
              <Text
                style={{
                  color: '#a1a1aa',
                  fontSize: 12,
                  fontWeight: '600',
                  textTransform: 'uppercase',
                  marginBottom: 8,
                }}
              >
                Prompt
              </Text>
              <TextInput
                value={prompt}
                onChangeText={setPrompt}
                placeholder="What should the agent do?"
                placeholderTextColor="#52525b"
                multiline
                editable={!isSubmitting}
                style={{
                  backgroundColor: '#27272a',
                  borderRadius: 10,
                  padding: 12,
                  color: 'white',
                  fontSize: 15,
                  minHeight: 100,
                  textAlignVertical: 'top',
                  marginBottom: 18,
                }}
                accessibilityLabel="Task prompt"
                accessibilityHint="Describe what the cloud agent should do"
              />

              {/* Submit button */}
              <Pressable
                onPress={() => void handleSubmit()}
                disabled={!canSubmit}
                style={{
                  backgroundColor: canSubmit ? '#f97316' : '#3f3f46',
                  borderRadius: 12,
                  paddingVertical: 14,
                  alignItems: 'center',
                }}
                accessibilityRole="button"
                accessibilityState={{ disabled: !canSubmit }}
                accessibilityLabel="Submit cloud task"
              >
                {isSubmitting ? (
                  <ActivityIndicator size="small" color="white" />
                ) : (
                  <Text style={{ color: 'white', fontSize: 15, fontWeight: '700' }}>
                    Submit Task
                  </Text>
                )}
              </Pressable>
            </ScrollView>
          </View>
        </View>
      </KeyboardAvoidingView>
    </Modal>
  );
}
