import type { NextConfig } from 'next';
import withSerwistInit from '@serwist/next';

/**
 * Content-Security-Policy header value.
 *
 * WHY: CSP mitigates XSS and data injection attacks by restricting which
 * sources the browser is allowed to load resources from.
 *
 * - `unsafe-inline` is required for inline styles generated by Tailwind CSS
 *   and Next.js hydration scripts (App Router injects inline scripts).
 * - `unsafe-eval` is NOT included -- Next.js App Router production builds
 *   do not require eval(). Removing it prevents XSS via string-to-code.
 * - `connect-src` includes Supabase (REST + Realtime WebSocket), Polar
 *   billing API, and Expo push notification service.
 * - `worker-src 'self'` allows service worker registration from the same origin.
 * - `frame-ancestors 'none'` prevents clickjacking (mirrors X-Frame-Options: DENY).
 * - `object-src 'none'` prevents Flash/plugin-based attacks.
 * - `base-uri 'self'` prevents base tag hijacking.
 * - `form-action 'self'` restricts where forms can submit to.
 */
const cspHeader = [
  "default-src 'self'",
  // A-006: 'unsafe-inline' is required for Next.js App Router hydration scripts.
  // Next.js injects inline <script> tags for page hydration, route prefetching,
  // and RSC payload delivery that cannot be given nonces without ejecting from
  // the framework's rendering pipeline. Nonce-based CSP via middleware is the
  // ideal fix but requires framework-level support for nonce propagation to all
  // hydration scripts, which Next.js 15 does not fully support for App Router.
  // 'unsafe-eval' is NOT included -- production builds do not require eval().
  // TODO: Revisit when Next.js adds native nonce support for App Router scripts.
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.polar.sh https://exp.host",
  // WHY: worker-src 'self' is required for the PWA service worker (sw.js).
  // Without it, the browser blocks navigator.serviceWorker.register() calls.
  "worker-src 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');

/**
 * Serwist (service worker) integration for PWA support.
 *
 * WHY: Wrapping the Next.js config with withSerwist injects a Webpack plugin
 * that compiles the service worker entry point (src/sw.ts) into public/sw.js
 * at build time, with a precache manifest of all static assets.
 *
 * - swSrc: The TypeScript source for the service worker.
 * - swDest: Where the compiled JS is written (must be in public/ for same-origin).
 * - additionalPrecacheEntries: The offline fallback page is precached so it is
 *   always available when the user loses connectivity.
 * - disable: Service workers are disabled in development to avoid stale cache issues.
 */
const withSerwist = withSerwistInit({
  swSrc: 'src/sw.ts',
  swDest: 'public/sw.js',
  additionalPrecacheEntries: [{ url: '/offline', revision: crypto.randomUUID() }],
  disable: process.env.NODE_ENV === 'development',
});

const nextConfig: NextConfig = {
  // Disable X-Powered-By header for security
  poweredByHeader: false,

  // FIX-037: Disable source maps in production
  // WHY: Source maps expose original source code, making it easier for
  // attackers to find vulnerabilities. Server source maps are already
  // disabled by default; this ensures client-side maps are too.
  productionBrowserSourceMaps: false,

  // Strict mode for React
  reactStrictMode: true,

  // Optimize package imports for smaller bundles
  experimental: {
    optimizePackageImports: ['recharts', '@supabase/supabase-js', 'lucide-react'],
  },

  // Image optimization
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '*.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
    ],
  },

  /**
   * Custom response headers for security, caching, and deep linking.
   *
   * Rule sets (applied in order, all matching rules are merged):
   * 1. Global security headers on all routes (CSP, X-Frame-Options, etc.)
   * 2. Public marketing pages: aggressive CDN caching to avoid SSR per bot request
   * 3. Blog articles: 4-hour CDN cache with 24-hour stale-while-revalidate
   * 4. Docs pages: 4-hour CDN cache with 24-hour stale-while-revalidate
   * 5. Dashboard: no cache (authenticated, dynamic, must never be served stale)
   * 6. API routes: strict CORS
   * 7. iOS/Android deep link files: correct Content-Type
   *
   * WHY aggressive caching for public pages:
   * AI crawlers and search bots can generate thousands of SSR requests per hour.
   * Setting s-maxage=3600 lets Vercel's CDN edge serve cached HTML without
   * invoking a serverless function. The crawler sees a 200, content gets indexed,
   * and Vercel bills zero additional compute. stale-while-revalidate=86400 means
   * Vercel can serve a slightly stale page while fetching a fresh one in the
   * background -- users never see a delay.
   *
   * WHY no-store for dashboard:
   * Dashboard pages contain authenticated user data. Caching them at the CDN
   * edge would mean one user's data could be served to another. private+no-store
   * ensures every dashboard request hits a fresh serverless render.
   */
  async headers() {
    return [
      {
        // Global security headers applied to every route
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: cspHeader,
          },
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
        ],
      },
      {
        // Public marketing pages: 1-hour CDN cache, 1-day stale-while-revalidate
        // WHY: These pages are static in practice (updated only on deploy) and are
        // the primary crawl targets. Caching them at the Vercel edge means bot
        // traffic does not trigger new serverless renders.
        source: '/(|features|pricing|security|security/compare|privacy|terms|dpa)',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=3600, stale-while-revalidate=86400',
          },
        ],
      },
      {
        // Blog articles: 4-hour CDN cache, 1-day stale-while-revalidate
        // WHY: Blog content is static at build time (generateStaticParams).
        // A 4-hour cache is long enough to absorb crawler bursts while staying
        // fresh enough that new articles appear within hours of publishing.
        source: '/blog/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=14400, stale-while-revalidate=86400',
          },
        ],
      },
      {
        // Docs pages: 4-hour CDN cache, 1-day stale-while-revalidate
        // WHY: Documentation content changes infrequently. Same reasoning as blog.
        source: '/docs/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=14400, stale-while-revalidate=86400',
          },
        ],
      },
      {
        // Dashboard: never cache at CDN (authenticated, personalized, dynamic)
        // WHY: CDN caching authenticated pages is a critical data-leakage risk.
        // private prevents CDN storage; no-cache forces revalidation with the
        // origin on every request; no-store disallows any intermediate storage.
        source: '/dashboard/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'private, no-cache, no-store',
          },
        ],
      },
      {
        // FIX-066: Restrict CORS on API routes
        // WHY: Without explicit CORS headers, browsers may allow
        // cross-origin requests from any domain. Restricting to
        // same-origin prevents unauthorized API access from malicious sites.
        source: '/api/:path*',
        headers: [
          {
            key: 'Access-Control-Allow-Origin',
            value: process.env.NEXT_PUBLIC_APP_URL || 'https://styrbyapp.com',
          },
          {
            key: 'Access-Control-Allow-Methods',
            value: 'GET, POST, PATCH, DELETE, OPTIONS',
          },
          {
            key: 'Access-Control-Allow-Headers',
            value: 'Content-Type, Authorization',
          },
        ],
      },
      {
        // WHY: iOS requires apple-app-site-association to be served as
        // application/json without an .json extension. Without this header,
        // Next.js may serve it as text/html which breaks Universal Links.
        source: '/.well-known/apple-app-site-association',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
          },
        ],
      },
      {
        // WHY: Android requires assetlinks.json to be served as
        // application/json for App Links verification to succeed.
        source: '/.well-known/assetlinks.json',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
          },
        ],
      },
    ];
  },
};

export default withSerwist(nextConfig);
