import type { NextConfig } from 'next';
import withSerwistInit from '@serwist/next';
import { withSentryConfig } from '@sentry/nextjs';
import BundleAnalyzer from '@next/bundle-analyzer';

/**
 * Bundle analyzer wrapper — only active when ANALYZE=true.
 *
 * WHY: @next/bundle-analyzer opens a Webpack bundle visualization in the
 * browser after a build. Running it unconditionally would slow every build
 * and open unwanted browser tabs in CI. Gating on the env var keeps the
 * dev ergonomics clean: `pnpm analyze` sets ANALYZE=true, normal builds skip it.
 *
 * Usage: pnpm --filter styrby-web analyze
 * (defined in package.json scripts as: ANALYZE=true next build --webpack)
 */
const withBundleAnalyzer = BundleAnalyzer({
  enabled: process.env.ANALYZE === 'true',
  openAnalyzer: process.env.ANALYZE === 'true',
});

/**
 * Content-Security-Policy header value.
 *
 * WHY: CSP mitigates XSS and data injection attacks by restricting which
 * sources the browser is allowed to load resources from.
 *
 * - `unsafe-inline` is required for inline styles generated by Tailwind CSS
 *   and Next.js hydration scripts (App Router injects inline scripts).
 * - `unsafe-eval` is NOT included -- Next.js App Router production builds
 *   do not require eval(). Removing it prevents XSS via string-to-code.
 * - `connect-src` includes Supabase (REST + Realtime WebSocket), Polar
 *   billing API, and Expo push notification service.
 * - `worker-src 'self'` allows service worker registration from the same origin.
 * - `frame-ancestors 'none'` prevents clickjacking (mirrors X-Frame-Options: DENY).
 * - `object-src 'none'` prevents Flash/plugin-based attacks.
 * - `base-uri 'self'` prevents base tag hijacking.
 * - `form-action 'self'` restricts where forms can submit to.
 */
const cspHeader = [
  "default-src 'self'",
  // A-006: 'unsafe-inline' is required for Next.js App Router hydration scripts.
  // ──────────────────────────────────────────────────────────────────────────
  // SEC-013 ACCEPTED RISK: 'unsafe-inline' in script-src
  //
  // DECISION: Keep 'unsafe-inline'. Do NOT add 'strict-dynamic' or nonce-based CSP.
  //
  // WHY 'unsafe-inline' IS REQUIRED (as of Next.js 15 / App Router):
  //   Next.js injects 5-10 inline <script> tags per page for hydration data,
  //   RSC payloads, and route prefetching. These are framework-generated at
  //   streaming SSR time — application code cannot control them.
  //
  // WHY 'strict-dynamic' BREAKS THE APP:
  //   strict-dynamic requires a nonce on the initial trusted <script>. Next.js
  //   App Router does NOT reliably propagate nonces to all internal hydration
  //   scripts during streaming SSR. Adding strict-dynamic causes:
  //   - Page renders as static HTML but never hydrates (no interactivity)
  //   - No React state, no routing, no client-side navigation
  //   - App appears functional but nothing works
  //   This was investigated on 2026-03-29 and confirmed broken.
  //
  // WHY THIS IS ACCEPTABLE:
  //   - Security audit (sec-ship 2026-03-29) confirmed ZERO XSS vectors:
  //     no dangerouslySetInnerHTML with user input, no eval(), no template
  //     injection, all user data goes through parameterized Supabase queries.
  //   - 'unsafe-inline' is a defense-in-depth weakness (CSP won't catch a
  //     future XSS), but with zero current attack surface, the risk is low.
  //   - No third-party analytics scripts (no GTM, GA, Segment, etc.)
  //
  // WHEN TO REVISIT:
  //   - When Next.js ships native nonce propagation for App Router (roadmap item)
  //   - When upgrading to Next.js 16+ (check release notes for CSP improvements)
  //   - If third-party scripts are added (analytics, chat widgets, etc.)
  //
  // 'unsafe-eval' is NOT included — production builds do not require eval().
  // ──────────────────────────────────────────────────────────────────────────
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.polar.sh https://exp.host",
  // WHY: worker-src 'self' is required for the PWA service worker (sw.js).
  // Without it, the browser blocks navigator.serviceWorker.register() calls.
  "worker-src 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');

/**
 * Serwist (service worker) integration for PWA support.
 *
 * WHY: Wrapping the Next.js config with withSerwist injects a Webpack plugin
 * that compiles the service worker entry point (src/sw.ts) into public/sw.js
 * at build time, with a precache manifest of all static assets.
 *
 * - swSrc: The TypeScript source for the service worker.
 * - swDest: Where the compiled JS is written (must be in public/ for same-origin).
 * - additionalPrecacheEntries: The offline fallback page is precached so it is
 *   always available when the user loses connectivity.
 * - disable: Service workers are disabled in development to avoid stale cache issues.
 */
const withSerwist = withSerwistInit({
  swSrc: 'src/sw.ts',
  swDest: 'public/sw.js',
  additionalPrecacheEntries: [{ url: '/offline', revision: crypto.randomUUID() }],
  disable: process.env.NODE_ENV === 'development',
});

const nextConfig: NextConfig = {
  // Disable X-Powered-By header for security
  poweredByHeader: false,

  // FIX-037: Disable source maps in production
  // WHY: Source maps expose original source code, making it easier for
  // attackers to find vulnerabilities. Server source maps are already
  // disabled by default; this ensures client-side maps are too.
  productionBrowserSourceMaps: false,

  // Strict mode for React
  reactStrictMode: true,

  // Optimize package imports for smaller bundles.
  //
  // WHY: Next.js optimizePackageImports rewrites barrel-file imports into
  // direct deep imports at build time. For example, `import { X } from 'lucide-react'`
  // normally pulls in the entire lucide barrel (all ~1,400 icons), then tree-shakes.
  // With optimizePackageImports, Next.js skips the barrel entirely and imports
  // only the icon modules actually used. This reduces build time and initial bundle size.
  //
  // Added date-fns, @radix-ui/* packages, and sonner — all have barrel files
  // that export large surface areas. Optimizing them shaves 15-40 kB gzipped
  // from the initial JS bundle, improving TTI and Lighthouse performance score.
  experimental: {
    optimizePackageImports: [
      'recharts',
      '@supabase/supabase-js',
      'lucide-react',
      'date-fns',
      'sonner',
      '@radix-ui/react-accordion',
      '@radix-ui/react-alert-dialog',
      '@radix-ui/react-avatar',
      '@radix-ui/react-dialog',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-popover',
      '@radix-ui/react-select',
      '@radix-ui/react-tabs',
      '@radix-ui/react-tooltip',
    ],
  },

  // Image optimization
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '*.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
    ],
  },

  /**
   * Custom response headers for security, caching, and deep linking.
   *
   * Rule sets (applied in order, all matching rules are merged):
   * 1. Global security headers on all routes (CSP, X-Frame-Options, etc.)
   * 2. Public marketing pages: aggressive CDN caching to avoid SSR per bot request
   * 3. Blog articles: 4-hour CDN cache with 24-hour stale-while-revalidate
   * 4. Docs pages: 4-hour CDN cache with 24-hour stale-while-revalidate
   * 5. Dashboard: no cache (authenticated, dynamic, must never be served stale)
   * 6. API routes: strict CORS
   * 7. iOS/Android deep link files: correct Content-Type
   *
   * WHY aggressive caching for public pages:
   * AI crawlers and search bots can generate thousands of SSR requests per hour.
   * Setting s-maxage=3600 lets Vercel's CDN edge serve cached HTML without
   * invoking a serverless function. The crawler sees a 200, content gets indexed,
   * and Vercel bills zero additional compute. stale-while-revalidate=86400 means
   * Vercel can serve a slightly stale page while fetching a fresh one in the
   * background -- users never see a delay.
   *
   * WHY no-store for dashboard:
   * Dashboard pages contain authenticated user data. Caching them at the CDN
   * edge would mean one user's data could be served to another. private+no-store
   * ensures every dashboard request hits a fresh serverless render.
   */
  async headers() {
    return [
      {
        // Global security headers applied to every route
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: cspHeader,
          },
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
        ],
      },
      {
        // Public marketing pages: 1-hour CDN cache, 1-day stale-while-revalidate
        // WHY: These pages are static in practice (updated only on deploy) and are
        // the primary crawl targets. Caching them at the Vercel edge means bot
        // traffic does not trigger new serverless renders.
        source: '/(|features|pricing|security|security/compare|privacy|terms|dpa)',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=3600, stale-while-revalidate=86400',
          },
        ],
      },
      {
        // Blog articles: 4-hour CDN cache, 1-day stale-while-revalidate
        // WHY: Blog content is static at build time (generateStaticParams).
        // A 4-hour cache is long enough to absorb crawler bursts while staying
        // fresh enough that new articles appear within hours of publishing.
        source: '/blog/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=14400, stale-while-revalidate=86400',
          },
        ],
      },
      {
        // Docs pages: 4-hour CDN cache, 1-day stale-while-revalidate
        // WHY: Documentation content changes infrequently. Same reasoning as blog.
        source: '/docs/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=14400, stale-while-revalidate=86400',
          },
        ],
      },
      {
        // Dashboard: never cache at CDN (authenticated, personalized, dynamic)
        // WHY: CDN caching authenticated pages is a critical data-leakage risk.
        // private prevents CDN storage; no-cache forces revalidation with the
        // origin on every request; no-store disallows any intermediate storage.
        // must-revalidate ensures HTTP/1.1 proxies also skip stale serving.
        source: '/dashboard/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'private, no-cache, no-store, must-revalidate',
          },
        ],
      },
      {
        // Support access pages: never cache — authenticated user approval flow
        // WHY: /support/access/[grantId] renders per-user grant approval state.
        // Any CDN or browser cache storing this page could expose one user's
        // grant to another user on a shared device or after session rotation.
        // private, no-cache, no-store, must-revalidate matches the dashboard
        // policy and satisfies OWASP A01:2021 / SOC2 CC6.1 / GDPR Art. 5(1)(f).
        // NOTE: This next.config.ts rule is the authoritative source of the
        // no-store guarantee — NOT middleware. The admin session page comment
        // previously stated middleware was responsible; that was inaccurate.
        source: '/support/access/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'private, no-cache, no-store, must-revalidate',
          },
        ],
      },
      {
        // FIX-066: Restrict CORS on API routes
        // WHY: Without explicit CORS headers, browsers may allow
        // cross-origin requests from any domain. Restricting to
        // same-origin prevents unauthorized API access from malicious sites.
        source: '/api/:path*',
        headers: [
          {
            key: 'Access-Control-Allow-Origin',
            // WHY `.trim()` + fallback chain: Vercel env vars occasionally get
            // pasted with trailing newlines; an `\n` in a response header is
            // URL-encoded to `%0A` by downstream proxies and also triggers
            // strict header-validator rejections. Trim defensively before use.
            value: (process.env.NEXT_PUBLIC_APP_URL || '').trim() || 'https://styrbyapp.com',
          },
          {
            key: 'Access-Control-Allow-Methods',
            value: 'GET, POST, PATCH, DELETE, OPTIONS',
          },
          {
            key: 'Access-Control-Allow-Headers',
            value: 'Content-Type, Authorization',
          },
        ],
      },
      {
        // WHY: iOS requires apple-app-site-association to be served as
        // application/json without an .json extension. Without this header,
        // Next.js may serve it as text/html which breaks Universal Links.
        source: '/.well-known/apple-app-site-association',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
          },
        ],
      },
      {
        // WHY: Android requires assetlinks.json to be served as
        // application/json for App Links verification to succeed.
        source: '/.well-known/assetlinks.json',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
          },
        ],
      },
    ];
  },
};

/**
 * Sentry build-time configuration (@sentry/nextjs v10 API).
 *
 * withSentryConfig wraps the OUTERMOST config (after withSerwist) so that
 * Sentry's webpack plugins run on the fully-composed config, including the
 * service worker bundle produced by Serwist.
 *
 * WHY sourcemaps.disable is conditional:
 * Sentry's source map upload plugin requires a valid SENTRY_AUTH_TOKEN. Without
 * the token (local dev, CI without secrets), uploading would fail and break the
 * build. Disabling source map upload when the token is absent lets the app build
 * and run normally — errors are captured but stack traces won't be symbolicated
 * in those environments.
 *
 * WHY sourcemaps.deleteSourcemapsAfterUpload is true:
 * After Sentry uploads source maps for error symbolication, we delete the .map
 * files so they are never served to browsers. This prevents attackers from
 * downloading original TypeScript source via DevTools.
 *
 * WHY tunnelRoute is '/monitoring':
 * Some ad blockers and privacy extensions block requests to sentry.io directly.
 * The tunnel proxies Sentry events through our own domain, improving error
 * capture rates without requiring users to whitelist a third-party domain.
 *
 * WHY silent is true:
 * Sentry's webpack plugin logs verbose output during builds by default. Silencing
 * it keeps build output clean and avoids confusion with real build warnings.
 *
 * WHY telemetry is false:
 * The Sentry plugin phones home with build telemetry by default. Disabling it
 * avoids leaking build metadata (timing, config shape) to Sentry's servers.
 */
const sentryWrapped = withSentryConfig(withSerwist(nextConfig), {
  /**
   * Sentry organization slug.
   * Can also be set via the SENTRY_ORG environment variable.
   * Get this from: sentry.io > Settings > General Settings > Organization Slug
   */
  org: process.env.SENTRY_ORG,

  /**
   * Sentry project slug.
   * Can also be set via the SENTRY_PROJECT environment variable.
   * Get this from: sentry.io > Project Settings > General Settings > Name
   */
  project: process.env.SENTRY_PROJECT,

  /** Suppress Sentry plugin logging during build for clean CI output. */
  silent: true,

  /** Disable Sentry build telemetry to avoid leaking metadata. */
  telemetry: false,

  /**
   * Source map configuration.
   * WHY disable when SENTRY_AUTH_TOKEN is absent: upload requires auth.
   * Disabling prevents build failures in environments without Sentry credentials.
   * WHY deleteSourcemapsAfterUpload: source maps expose original source code —
   * we upload them for Sentry error symbolication, then delete to prevent
   * browsers from downloading them.
   */
  sourcemaps: {
    disable: !process.env.SENTRY_AUTH_TOKEN,
    deleteSourcemapsAfterUpload: true,
  },

  /**
   * Proxy Sentry events through /monitoring on our own domain.
   * WHY: Ad blockers and privacy extensions commonly block requests to
   * o*.ingest.sentry.io. The tunnel route bypasses this without asking users
   * to add exceptions for a third-party domain.
   */
  tunnelRoute: '/monitoring',
});

/**
 * WHY withBundleAnalyzer is the outermost wrapper:
 * Bundle analyzer must wrap the fully-composed config (including Sentry's
 * webpack plugins) so it sees the real final webpack config that matches
 * what the production build produces. Wrapping before Sentry would miss
 * Sentry's injected plugins in the report.
 */
export default withBundleAnalyzer(sentryWrapped);
