import type { NextConfig } from 'next';

/**
 * Content-Security-Policy header value.
 *
 * WHY: CSP mitigates XSS and data injection attacks by restricting which
 * sources the browser is allowed to load resources from.
 *
 * - `unsafe-inline` and `unsafe-eval` are required for Next.js hydration and
 *   inline styles generated by frameworks like Tailwind CSS.
 * - `connect-src` includes Supabase (REST + Realtime WebSocket), Polar
 *   billing API, and Expo push notification service.
 * - `frame-ancestors 'none'` prevents clickjacking (mirrors X-Frame-Options: DENY).
 */
const cspHeader = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.polar.sh https://exp.host",
  "frame-ancestors 'none'",
].join('; ');

const nextConfig: NextConfig = {
  // Disable X-Powered-By header for security
  poweredByHeader: false,

  // Strict mode for React
  reactStrictMode: true,

  // Optimize package imports for smaller bundles
  experimental: {
    optimizePackageImports: ['recharts', '@supabase/supabase-js'],
  },

  // Image optimization
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '*.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
    ],
  },

  /**
   * Custom response headers for security and deep linking.
   *
   * Three rule sets:
   * 1. Global security headers on all routes (CSP, X-Frame-Options, etc.)
   * 2. apple-app-site-association served as application/json (iOS Universal Links)
   * 3. assetlinks.json served as application/json (Android App Links)
   */
  async headers() {
    return [
      {
        // Global security headers applied to every route
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: cspHeader,
          },
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
        ],
      },
      {
        // WHY: iOS requires apple-app-site-association to be served as
        // application/json without an .json extension. Without this header,
        // Next.js may serve it as text/html which breaks Universal Links.
        source: '/.well-known/apple-app-site-association',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
          },
        ],
      },
      {
        // WHY: Android requires assetlinks.json to be served as
        // application/json for App Links verification to succeed.
        source: '/.well-known/assetlinks.json',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/json',
          },
        ],
      },
    ];
  },
};

export default nextConfig;
