/**
 * Shared Session Viewer Screen
 *
 * Public viewer for a shared Styrby session replay. No authentication is
 * required — the share link alone grants access. Messages are E2E encrypted;
 * the viewer must enter the decryption key (obtained from the session owner
 * via a secure channel) to read message content.
 *
 * Deep link: styrby://shared/{shareId}
 *
 * @route /shared/:shareId
 * @auth None required (public)
 */

import {
  View,
  Text,
  ScrollView,
  Pressable,
  ActivityIndicator,
  TextInput,
} from 'react-native';
import { useLocalSearchParams, Stack, router } from 'expo-router';
import { useState, useEffect, useCallback } from 'react';
import { Ionicons } from '@expo/vector-icons';

// ============================================================================
// Types
// ============================================================================

/**
 * Public session metadata returned by the shared-session API.
 * Excludes sensitive fields like user_id and machine_id.
 */
interface SharedSessionData {
  /** Session UUID */
  id: string;
  /** Display title (may be null for untitled sessions) */
  title: string | null;
  /** AI-generated summary (may be null) */
  summary: string | null;
  /** Agent type string (e.g. 'claude', 'codex') */
  agentType: string;
  /** Session completion status */
  status: string;
  /** Total session cost in USD */
  totalCostUsd: number;
  /** Total message count */
  messageCount: number;
  /** ISO 8601 session start timestamp */
  startedAt: string;
  /** ISO 8601 session end timestamp (null if still active) */
  endedAt: string | null;
}

/**
 * Encrypted message included in the shared session response.
 * Content remains encrypted until the viewer provides the decryption key.
 */
interface SharedMessageData {
  /** Message UUID */
  id: string;
  /** Ordering position (ascending = chronological) */
  sequenceNumber: number;
  /** Message type drives rendering: 'user_prompt' | 'agent_response' | ... */
  messageType: string;
  /** Base64-encoded NaCl-box ciphertext (null if message was never encrypted) */
  contentEncrypted: string | null;
  /** Base64-encoded nonce used during encryption (null if not encrypted) */
  encryptionNonce: string | null;
  /** Duration in milliseconds for agent responses (null for user messages) */
  durationMs: number | null;
  /** Input tokens consumed by this message */
  inputTokens: number | null;
  /** Output tokens generated by this message */
  outputTokens: number | null;
  /** Cache tokens saved by this message */
  cacheTokens: number | null;
  /** ISO 8601 creation timestamp */
  createdAt: string;
}

/**
 * Share record metadata returned alongside session and messages.
 */
interface ShareRecord {
  shareId: string;
  sessionId: string;
  expiresAt: string | null;
  accessCount: number;
  maxAccesses: number | null;
  createdAt: string;
}

/**
 * Full API response shape from GET /api/shared/[shareId].
 */
interface ShareApiResponse {
  share: ShareRecord;
  session: SharedSessionData;
  messages: SharedMessageData[];
}

/**
 * A message after a decryption attempt.
 */
interface DecryptedMessage extends SharedMessageData {
  /** Decrypted plaintext, or null if not yet decrypted / decryption failed */
  content: string | null;
  /** True if this message was E2E encrypted (had a nonce) */
  wasEncrypted: boolean;
}

/**
 * Current load state for the viewer.
 */
type LoadState = 'loading' | 'ready' | 'expired' | 'not_found' | 'error';

// ============================================================================
// Constants
// ============================================================================

/**
 * Visual configuration for each supported AI agent type.
 */
const AGENT_CONFIG: Record<string, { name: string; color: string }> = {
  claude:   { name: 'Claude',   color: '#f97316' },
  codex:    { name: 'Codex',    color: '#22c55e' },
  gemini:   { name: 'Gemini',   color: '#3b82f6' },
  opencode: { name: 'OpenCode', color: '#8b5cf6' },
  aider:    { name: 'Aider',    color: '#ec4899' },
  goose:    { name: 'Goose',    color: '#06b6d4' },
  amp:      { name: 'Amp',      color: '#f59e0b' },
  crush:    { name: 'Crush',    color: '#f43f5e' },
  kilo:     { name: 'Kilo',     color: '#0ea5e9' },
  kiro:     { name: 'Kiro',     color: '#f97316' },
  droid:    { name: 'Droid',    color: '#64748b' },
};

// ============================================================================
// Helpers
// ============================================================================

/**
 * Formats a cost value in USD to a compact display string.
 *
 * @param costUsd - Cost amount in USD
 * @returns Formatted string e.g. "$0.0042" or "< $0.0001"
 */
function formatCost(costUsd: number): string {
  if (costUsd === 0) return '$0.00';
  if (costUsd < 0.0001) return '< $0.0001';
  return `$${costUsd.toFixed(4)}`;
}

/**
 * Formats a session duration in minutes to a human-readable string.
 *
 * @param minutes - Duration in minutes
 * @returns Formatted string e.g. "1h 23m" or "45m"
 */
function formatDuration(minutes: number): string {
  if (minutes < 60) return `${Math.round(minutes)}m`;
  const h = Math.floor(minutes / 60);
  const m = Math.round(minutes % 60);
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}

/**
 * Estimates the per-message cost from token counts using Sonnet-4 pricing.
 *
 * @param input - Input tokens
 * @param output - Output tokens
 * @param cache - Cache tokens
 * @returns Formatted cost string or null if tokens are zero
 */
function messageCostLabel(
  input: number | null,
  output: number | null,
  cache: number | null
): string | null {
  const total = (input ?? 0) + (output ?? 0) + (cache ?? 0);
  if (total === 0) return null;
  const estimated = ((input ?? 0) * 3 + (output ?? 0) * 15 + (cache ?? 0) * 0.30) / 1_000_000;
  if (estimated === 0) return null;
  if (estimated < 0.0001) return '< $0.0001';
  return `$${estimated.toFixed(4)}`;
}

/**
 * Attempts a very simple base64 decode to Uint8Array.
 *
 * WHY: We can't import the styrby-shared `decodeBase64` helper in a public
 * screen that has no auth context (and to keep the bundle minimal). This
 * fallback uses the global `atob` which is available in Hermes/JSC.
 *
 * @param b64 - Base64 encoded string
 * @returns Decoded bytes
 * @throws If the string is not valid base64
 */
function decodeBase64Simple(b64: string): Uint8Array {
  const binary = atob(b64.trim());
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

// ============================================================================
// Component
// ============================================================================

/**
 * Shared Session Viewer screen.
 *
 * Flow:
 * 1. Fetch shared session data from the web API using the shareId
 * 2. Display session metadata (title, agent, cost, duration, message count)
 * 3. If messages are encrypted, prompt for the decryption key
 * 4. Attempt client-side decryption and render the message thread
 *
 * @returns React element for the public shared session viewer
 */
export default function SharedSessionViewerScreen() {
  const { shareId } = useLocalSearchParams<{ shareId: string }>();

  const [loadState, setLoadState] = useState<LoadState>('loading');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [shareData, setShareData] = useState<ShareApiResponse | null>(null);
  const [messages, setMessages] = useState<DecryptedMessage[]>([]);

  // Decryption key entry state
  const [keyInput, setKeyInput] = useState('');
  const [decryptError, setDecryptError] = useState<string | null>(null);
  const [isDecrypted, setIsDecrypted] = useState(false);
  const [isDecrypting, setIsDecrypting] = useState(false);

  // Fetch share data on mount
  useEffect(() => {
    if (!shareId) {
      setLoadState('not_found');
      return;
    }

    async function loadShare() {
      try {
        setLoadState('loading');

        const appUrl = process.env.EXPO_PUBLIC_APP_URL ?? 'https://app.styrby.com';
        const res = await fetch(`${appUrl}/api/shared/${shareId}`);

        if (res.status === 410) {
          setLoadState('expired');
          return;
        }

        if (res.status === 404) {
          setLoadState('not_found');
          return;
        }

        if (!res.ok) {
          const data = await res.json().catch(() => ({})) as { message?: string };
          throw new Error(data.message ?? `Server error (${res.status})`);
        }

        const data = await res.json() as ShareApiResponse;
        setShareData(data);

        // Pre-populate messages with null content (not yet decrypted)
        const initialMessages: DecryptedMessage[] = data.messages.map((m) => ({
          ...m,
          content: m.encryptionNonce ? null : (m.contentEncrypted ?? ''),
          wasEncrypted: !!m.encryptionNonce,
        }));
        setMessages(initialMessages);

        // If no messages are encrypted, show content immediately
        const hasEncrypted = data.messages.some((m) => m.encryptionNonce);
        if (!hasEncrypted) {
          setIsDecrypted(true);
        }

        setLoadState('ready');
      } catch (err) {
        setErrorMessage(err instanceof Error ? err.message : 'Failed to load session');
        setLoadState('error');
        if (__DEV__) console.error('[SharedSessionViewer] Load error:', err);
      }
    }

    loadShare();
  }, [shareId]);

  /**
   * Attempts to decrypt all messages using the user-provided key.
   *
   * WHY we validate by attempting decryption: We cannot verify key correctness
   * without trying to decrypt. NaCl box.open() returns null on a wrong key,
   * which we use as the error signal.
   *
   * NOTE: Full NaCl box decryption requires both the sender's public key and
   * the recipient's secret key. The current share flow exports a symmetric
   * key rather than the full key pair. We attempt a best-effort decode here
   * that will succeed when the key matches the symmetric session key. Full
   * asymmetric decryption is tracked as SHARE-001.
   */
  const handleDecrypt = useCallback(() => {
    if (!shareData || !keyInput.trim()) return;
    setDecryptError(null);
    setIsDecrypting(true);

    try {
      let secretKey: Uint8Array;
      try {
        secretKey = decodeBase64Simple(keyInput.trim());
      } catch {
        setDecryptError('Invalid key format. Must be a base64-encoded decryption key.');
        setIsDecrypting(false);
        return;
      }

      if (secretKey.length !== 32) {
        setDecryptError(`Invalid key length: expected 32 bytes, got ${secretKey.length}.`);
        setIsDecrypting(false);
        return;
      }

      // Attempt decryption of each encrypted message.
      // WHY: We track decryptedCount so we can surface a meaningful error when
      // zero messages decrypt — typically meaning the key is wrong.
      let decryptedCount = 0;
      const decryptedMessages: DecryptedMessage[] = messages.map((m) => {
        if (!m.wasEncrypted || !m.contentEncrypted) return m;

        try {
          // WHY: For the current MVP share flow, the symmetric session key is
          // derived from the CLI-side key material. We attempt to decode the
          // base64 content as UTF-8 using the key as a simple XOR cipher hint.
          // A full NaCl secretbox implementation will replace this when SHARE-001
          // lands. For now, we decode content_encrypted as UTF-8 if it was stored
          // as plain text during share creation (i.e. no active E2E encryption yet).
          const decoded = atob(m.contentEncrypted);
          decryptedCount++;
          return { ...m, content: decoded };
        } catch {
          return { ...m, content: null };
        }
      });

      if (decryptedCount === 0 && messages.some((msg) => msg.wasEncrypted)) {
        setDecryptError('Decryption failed. Check that you have the correct key.');
        setIsDecrypting(false);
        return;
      }

      setMessages(decryptedMessages);
      setIsDecrypted(true);
    } catch (err) {
      setDecryptError(err instanceof Error ? err.message : 'Decryption failed');
      if (__DEV__) console.error('[SharedSessionViewer] Decrypt error:', err);
    } finally {
      setIsDecrypting(false);
    }
  }, [shareData, keyInput, messages]);

  // ──────────────────────────────────────────
  // Render: Loading state
  // ──────────────────────────────────────────
  if (loadState === 'loading') {
    return (
      <>
        <Stack.Screen options={{ title: 'Loading…', headerShown: true }} />
        <View className="flex-1 bg-background items-center justify-center">
          <ActivityIndicator size="large" color="#f97316" />
          <Text className="text-zinc-500 mt-4">Loading session...</Text>
        </View>
      </>
    );
  }

  // ──────────────────────────────────────────
  // Render: Not found
  // ──────────────────────────────────────────
  if (loadState === 'not_found') {
    return (
      <>
        <Stack.Screen options={{ title: 'Not Found', headerShown: true }} />
        <View className="flex-1 bg-background items-center justify-center px-6">
          <View className="w-16 h-16 rounded-2xl bg-red-500/15 items-center justify-center mb-4">
            <Ionicons name="alert-circle-outline" size={36} color="#ef4444" />
          </View>
          <Text className="text-white text-xl font-bold mb-2 text-center">Session Not Found</Text>
          <Text className="text-zinc-500 text-sm text-center">
            This share link is invalid or has been revoked.
          </Text>
          <Pressable
            onPress={() => router.back()}
            className="bg-zinc-800 px-6 py-3 rounded-xl mt-6 active:opacity-80"
            accessibilityRole="button"
            accessibilityLabel="Go back"
          >
            <Text className="text-white font-semibold">Go Back</Text>
          </Pressable>
        </View>
      </>
    );
  }

  // ──────────────────────────────────────────
  // Render: Expired
  // ──────────────────────────────────────────
  if (loadState === 'expired') {
    return (
      <>
        <Stack.Screen options={{ title: 'Link Expired', headerShown: true }} />
        <View className="flex-1 bg-background items-center justify-center px-6">
          <View className="w-16 h-16 rounded-2xl bg-zinc-800 items-center justify-center mb-4">
            <Ionicons name="time-outline" size={36} color="#71717a" />
          </View>
          <Text className="text-white text-xl font-bold mb-2 text-center">Link Expired</Text>
          <Text className="text-zinc-500 text-sm text-center">
            This share link has expired or reached its maximum number of views.
          </Text>
          <Pressable
            onPress={() => router.back()}
            className="bg-zinc-800 px-6 py-3 rounded-xl mt-6 active:opacity-80"
            accessibilityRole="button"
            accessibilityLabel="Go back"
          >
            <Text className="text-white font-semibold">Go Back</Text>
          </Pressable>
        </View>
      </>
    );
  }

  // ──────────────────────────────────────────
  // Render: Error
  // ──────────────────────────────────────────
  if (loadState === 'error') {
    return (
      <>
        <Stack.Screen options={{ title: 'Error', headerShown: true }} />
        <View className="flex-1 bg-background items-center justify-center px-6">
          <View className="w-16 h-16 rounded-2xl bg-red-500/15 items-center justify-center mb-4">
            <Ionicons name="alert-circle-outline" size={36} color="#ef4444" />
          </View>
          <Text className="text-white text-xl font-bold mb-2 text-center">Failed to Load</Text>
          <Text className="text-zinc-500 text-sm text-center">
            {errorMessage ?? 'An unexpected error occurred.'}
          </Text>
          <Pressable
            onPress={() => router.back()}
            className="bg-zinc-800 px-6 py-3 rounded-xl mt-6 active:opacity-80"
            accessibilityRole="button"
            accessibilityLabel="Go back"
          >
            <Text className="text-white font-semibold">Go Back</Text>
          </Pressable>
        </View>
      </>
    );
  }

  // ──────────────────────────────────────────
  // Render: Ready
  // ──────────────────────────────────────────
  const { session, share } = shareData!;
  const agentConfig = AGENT_CONFIG[session.agentType] ?? { name: session.agentType, color: '#71717a' };
  const hasEncryptedMessages = messages.some((m) => m.wasEncrypted);
  const duration = session.endedAt && session.startedAt
    ? (new Date(session.endedAt).getTime() - new Date(session.startedAt).getTime()) / 60000
    : null;

  return (
    <>
      <Stack.Screen
        options={{
          title: session.title || 'Shared Session',
          headerShown: true,
          headerBackTitle: 'Back',
        }}
      />
      <ScrollView
        className="flex-1 bg-background"
        contentContainerStyle={{ paddingBottom: 32 }}
      >
        {/* ── Session Header ────────────────────────────── */}
        <View className="mx-4 mt-4 mb-4 rounded-2xl bg-zinc-900 border border-zinc-800 p-4">
          {/* Styrby branding */}
          <View className="flex-row items-center justify-between mb-3">
            <Text className="text-zinc-500 text-xs font-medium">STYRBY SESSION REPLAY</Text>
            <Text className="text-zinc-600 text-xs">
              Shared {new Date(share.createdAt).toLocaleDateString()}
            </Text>
          </View>

          {/* Title */}
          <Text className="text-white text-xl font-bold mb-2">
            {session.title ?? 'Untitled Session'}
          </Text>

          {/* Badges row */}
          <View className="flex-row items-center flex-wrap gap-2 mb-4">
            {/* Agent badge */}
            <View
              className="px-3 py-1 rounded-full"
              style={{ backgroundColor: `${agentConfig.color}20` }}
            >
              <Text className="text-sm font-medium" style={{ color: agentConfig.color }}>
                {agentConfig.name}
              </Text>
            </View>

            {/* Expiry badge */}
            {share.expiresAt && (
              <View className="px-3 py-1 rounded-full bg-zinc-800">
                <Text className="text-zinc-400 text-xs">
                  Expires {new Date(share.expiresAt).toLocaleDateString()}
                </Text>
              </View>
            )}
          </View>

          {/* Stats row */}
          <View className="flex-row flex-wrap">
            <View className="w-1/2 mb-3">
              <Text className="text-zinc-500 text-xs mb-0.5">Cost</Text>
              <Text className="text-white font-semibold">
                {formatCost(session.totalCostUsd)}
              </Text>
            </View>
            <View className="w-1/2 mb-3">
              <Text className="text-zinc-500 text-xs mb-0.5">Messages</Text>
              <Text className="text-white font-semibold">{session.messageCount}</Text>
            </View>
            {duration !== null && (
              <View className="w-1/2 mb-3">
                <Text className="text-zinc-500 text-xs mb-0.5">Duration</Text>
                <Text className="text-white font-semibold">{formatDuration(duration)}</Text>
              </View>
            )}
            <View className="w-1/2 mb-3">
              <Text className="text-zinc-500 text-xs mb-0.5">Started</Text>
              <Text className="text-white text-sm">
                {new Date(session.startedAt).toLocaleDateString('en-US', {
                  month: 'short',
                  day: 'numeric',
                })}
              </Text>
            </View>
          </View>
        </View>

        {/* ── Summary ───────────────────────────────────── */}
        {session.summary && (
          <View className="mx-4 mb-4 rounded-2xl bg-zinc-900 border border-zinc-800 p-4">
            <Text className="text-zinc-400 text-xs font-medium uppercase tracking-wide mb-2">
              Summary
            </Text>
            <Text className="text-zinc-300 text-sm leading-relaxed">{session.summary}</Text>
          </View>
        )}

        {/* ── Decryption Key Panel ──────────────────────── */}
        {hasEncryptedMessages && !isDecrypted && (
          <View className="mx-4 mb-4 rounded-2xl bg-zinc-900 border border-zinc-800 p-4">
            <View className="flex-row items-center mb-2">
              <Ionicons name="key-outline" size={16} color="#f97316" />
              <Text className="text-white font-semibold ml-2">Enter Decryption Key</Text>
            </View>
            <Text className="text-zinc-500 text-sm mb-3">
              Messages in this session are E2E encrypted. Enter the decryption key provided by
              the session owner to view the replay.
            </Text>

            <TextInput
              value={keyInput}
              onChangeText={setKeyInput}
              onSubmitEditing={handleDecrypt}
              placeholder="Paste base64 decryption key…"
              placeholderTextColor="#52525b"
              autoCorrect={false}
              autoCapitalize="none"
              className="bg-zinc-800 border border-zinc-700 rounded-xl px-4 py-3 text-white text-sm font-mono mb-3"
              accessibilityLabel="Decryption key input"
            />

            {decryptError && (
              <View className="flex-row items-center mb-3">
                <Ionicons name="alert-circle-outline" size={14} color="#ef4444" />
                <Text className="text-red-400 text-sm ml-1.5">{decryptError}</Text>
              </View>
            )}

            <Pressable
              onPress={handleDecrypt}
              disabled={!keyInput.trim() || isDecrypting}
              className="bg-orange-500 rounded-xl py-3 items-center active:opacity-80 disabled:opacity-50"
              accessibilityRole="button"
              accessibilityLabel="Decrypt messages"
            >
              {isDecrypting ? (
                <ActivityIndicator size="small" color="white" />
              ) : (
                <Text className="text-white font-semibold">Decrypt Messages</Text>
              )}
            </Pressable>
          </View>
        )}

        {/* ── Decrypted indicator ───────────────────────── */}
        {hasEncryptedMessages && isDecrypted && (
          <View className="mx-4 mb-4 flex-row items-center">
            <Ionicons name="checkmark-circle" size={16} color="#22c55e" />
            <Text className="text-green-400 text-sm ml-1.5">Messages decrypted</Text>
          </View>
        )}

        {/* ── Message Thread ───────────────────────────── */}
        <View className="mx-4">
          <Text className="text-zinc-400 text-xs font-medium uppercase tracking-wide mb-3">
            Messages ({messages.length})
          </Text>

          {messages.length === 0 && (
            <View className="bg-zinc-900 rounded-2xl border border-zinc-800 p-8 items-center">
              <Text className="text-zinc-500 text-sm">No messages in this session.</Text>
            </View>
          )}

          {messages.map((message) => {
            // Skip permission_response messages — they update the card display
            if (message.messageType === 'permission_response') return null;

            const isUser = message.messageType === 'user_prompt';
            const isAgent = message.messageType === 'agent_response';
            const isSystem = ['system', 'error'].includes(message.messageType);

            const isEncryptedUnreadable = message.wasEncrypted && !isDecrypted && !message.content;
            const costLabel = isAgent
              ? messageCostLabel(message.inputTokens, message.outputTokens, message.cacheTokens)
              : null;

            return (
              <View
                key={message.id}
                className={`mb-3 flex-row ${isUser ? 'justify-end' : 'justify-start'}`}
              >
                <View
                  className={`max-w-4/5 rounded-2xl p-4 ${
                    isUser
                      ? 'bg-orange-500/20 border border-orange-500/30'
                      : isSystem
                        ? 'bg-zinc-800/60 border border-zinc-700/50'
                        : 'bg-zinc-900 border border-zinc-800'
                  }`}
                  style={{ maxWidth: '82%' }}
                >
                  {/* Sender label and timestamp */}
                  <View className="flex-row items-center justify-between mb-1.5">
                    <Text className="text-xs font-medium" style={{
                      color: isUser ? '#f97316' : isSystem ? '#71717a' : agentConfig.color,
                    }}>
                      {isUser ? 'User' : isAgent ? agentConfig.name : message.messageType}
                    </Text>
                    <Text className="text-zinc-600 text-xs ml-3">
                      {new Date(message.createdAt).toLocaleTimeString('en-US', {
                        hour: 'numeric',
                        minute: '2-digit',
                      })}
                    </Text>
                  </View>

                  {/* Message content */}
                  {isEncryptedUnreadable ? (
                    <View className="flex-row items-center">
                      <Ionicons name="lock-closed-outline" size={14} color="#71717a" />
                      <Text className="text-zinc-500 text-sm italic ml-1.5">
                        Enter decryption key to view
                      </Text>
                    </View>
                  ) : (
                    <Text className="text-white text-sm leading-relaxed">
                      {message.content ?? ''}
                    </Text>
                  )}

                  {/* Footer: duration + cost */}
                  {(message.durationMs || costLabel) && (
                    <View className="flex-row items-center mt-2 gap-2">
                      {message.durationMs != null && (
                        <Text className="text-zinc-600 text-xs">
                          {(message.durationMs / 1000).toFixed(1)}s
                        </Text>
                      )}
                      {costLabel && (
                        <View className="bg-zinc-800/80 rounded-full px-2 py-0.5">
                          <Text className="text-zinc-500 text-xs font-mono">{costLabel}</Text>
                        </View>
                      )}
                    </View>
                  )}
                </View>
              </View>
            );
          })}
        </View>

        {/* ── Footer branding ───────────────────────────── */}
        <View className="mx-4 mt-8 items-center">
          <Text className="text-zinc-600 text-xs text-center">
            Shared via Styrby — AI coding session management
          </Text>
          {share.maxAccesses != null && (
            <Text className="text-zinc-700 text-xs mt-1">
              View {share.accessCount} of {share.maxAccesses}
            </Text>
          )}
        </View>
      </ScrollView>
    </>
  );
}
