/**
 * Uptime Recovery Email
 *
 * Operator-facing recovery notice dispatched by /api/cron/uptime-monitor
 * on the failure->success transition. The state transition is the
 * value: it tells the operator they can stop investigating without
 * having to log in. Voice matches the alert email (factual, ops-style).
 */

import { Section, Text } from '@react-email/components';
import * as React from 'react';
import { BaseLayout, Button, Heading, Paragraph, Divider } from './base-layout';

export interface UptimeRecoveryProps {
  /** The URL that recovered. */
  url: string;
  /** HTTP status of the recovery ping (typically 200). */
  statusCode: number;
  /** Human label for total downtime, e.g. "12m" or "2h 14m". */
  downForLabel: string;
  /** ISO timestamp the outage started (alert_sent_at). */
  downSinceIso: string;
  /** ISO timestamp recovery was detected (cron tick time). */
  recoveredAtIso: string;
  /** Round-trip duration of the successful ping, in milliseconds. */
  responseTimeMs: number;
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <tr>
      <td
        style={{
          padding: '8px 12px',
          fontSize: '13px',
          color: '#a1a1aa',
          borderBottom: '1px solid #27272a',
        }}
      >
        {label}
      </td>
      <td
        style={{
          padding: '8px 12px',
          fontSize: '13px',
          color: '#f4f4f5',
          fontWeight: 600,
          textAlign: 'right',
          borderBottom: '1px solid #27272a',
        }}
      >
        {value}
      </td>
    </tr>
  );
}

export default function UptimeRecoveryEmail(props: UptimeRecoveryProps) {
  const {
    url,
    statusCode,
    downForLabel,
    downSinceIso,
    recoveredAtIso,
    responseTimeMs,
  } = props;

  return (
    <BaseLayout preview={`Recovered: ${url} back to ${statusCode}`}>
      <Heading>Recovered: {url}</Heading>
      <Paragraph>
        The URL is back to HTTP {statusCode} after approximately
        {' '}
        {downForLabel} of failed checks. No further action required from
        the uptime monitor; if you investigated, document the root cause
        in the project lessons-learned doc.
      </Paragraph>

      <Section
        style={{
          backgroundColor: '#18181b',
          borderRadius: '8px',
          padding: '8px 4px',
          marginBottom: '20px',
          border: '1px solid #27272a',
        }}
      >
        <table
          cellPadding={0}
          cellSpacing={0}
          style={{ width: '100%', borderCollapse: 'collapse' }}
        >
          <tbody>
            <Row label="URL" value={url} />
            <Row label="Status" value={`HTTP ${statusCode}`} />
            <Row label="Down for" value={downForLabel} />
            <Row label="Down since" value={downSinceIso} />
            <Row label="Recovered at" value={recoveredAtIso} />
            <Row label="Response time" value={`${responseTimeMs}ms`} />
          </tbody>
        </table>
      </Section>

      <Section style={{ textAlign: 'center', marginBottom: '20px' }}>
        <Button href={url}>View live site</Button>
      </Section>

      <Divider />

      <Text style={{ margin: '0', fontSize: '11px', color: '#71717a' }}>
        Generated by /api/cron/uptime-monitor on the failure to success
        transition. One recovery email per outage; the next outage will
        produce a fresh alert + recovery pair.
      </Text>
    </BaseLayout>
  );
}
