/**
 * Tests for requestSupportAccessAction — actions.ts
 *
 * Phase 4.2 — Support Tooling T4
 * Updated 2026-04-25 — SEC-ADV-001 remediation:
 *   - Cookie-channel coverage replaced with admin_stash_grant_token coverage.
 *   - The action now performs two RPCs: admin_request_support_access (writes
 *     hash + grant row) followed by admin_stash_grant_token (writes raw token
 *     to the server-only support_grant_token_pickup table).
 *   - The non-HttpOnly cookie has been deleted from the action; tests verify
 *     no cookies API is touched at all.
 *
 * Coverage:
 *   (a) Zod validation — invalid inputs return { ok: false, field } without
 *       calling any RPC.
 *   (b) SQLSTATE mapping for admin_request_support_access — 42501 → "Not
 *       authorized", 22023 → "Invalid session…", 23514 → "Reason is required",
 *       unknown → "Internal error" + Sentry.
 *   (c) Happy path — calls request RPC then stash RPC with correct args; never
 *       writes a cookie; redirects to success URL.
 *   (d) Cross-user session rejection — 22023 from request RPC.
 *   (e) trustedTicketId integrity — bound URL ID is what reaches the request RPC.
 *   (f) Raw token never appears in the action return value or Sentry extras.
 *   (g) expires_in_hours bounds — 0 and 169 rejected; 1 and 168 accepted.
 *   (h) reason bounds — < 10 chars rejected; 10 chars accepted; > 500 chars rejected.
 *   (i) Stash RPC failure surfaces a user-facing error and skips the redirect.
 *   (j) Stash RPC receives the same grantId returned by request RPC and the
 *       same raw token generated by generateSupportToken.
 *
 * SOC 2 CC6.1 / CC7.2: admin action contract (auth check, audit, token safety)
 * is fully covered so compliance reviews can reference test output.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── Mocks ────────────────────────────────────────────────────────────────────

// WHY mock redirect as throwing: Next.js redirect() throws a special error
// internally to abort the current function. We replicate this so tests can
// assert "redirect was called" without needing a full Next.js render context.
const mockRedirect = vi.fn((url: string) => {
  throw new Error(`NEXT_REDIRECT:${url}`);
});
const mockRevalidatePath = vi.fn();

vi.mock('next/navigation', () => ({
  redirect: (url: string) => mockRedirect(url),
}));

vi.mock('next/cache', () => ({
  revalidatePath: (path: string) => mockRevalidatePath(path),
}));

// Static header values for deterministic IP + UA assertions.
const MOCK_XFF = '203.0.113.5, 10.0.0.1';
const MOCK_UA = 'Mozilla/5.0 test-support-agent';

const mockHeadersGet = vi.fn((name: string) => {
  if (name === 'x-forwarded-for') return MOCK_XFF;
  if (name === 'user-agent') return MOCK_UA;
  return null;
});

// WHY no cookies mock: the action no longer touches cookies (SEC-ADV-001).
// We mock next/headers with only `headers` so any accidental re-introduction
// of cookies() in the action will throw and surface in the test output.
vi.mock('next/headers', () => ({
  headers: async () => ({ get: mockHeadersGet }),
}));

// ─── Sentry mock ──────────────────────────────────────────────────────────────

const mockSentryCaptureException = vi.fn();
const mockSentryCaptureMessage = vi.fn();
vi.mock('@sentry/nextjs', () => ({
  captureException: (...args: unknown[]) => mockSentryCaptureException(...args),
  captureMessage: (...args: unknown[]) => mockSentryCaptureMessage(...args),
}));

// ─── Token mock ────────────────────────────────────────────────────────────────

const MOCK_RAW_TOKEN = 'mock-raw-token-aabbccdd-1122-3344-5566-778899aabbcc';
const MOCK_HASH = 'mock-sha256-hash-hex-64chars-aaaaaaaaaaaaaaaaaaaaaaaaaaaa0000';

vi.mock('@/lib/support/token', () => ({
  generateSupportToken: vi.fn(() => ({ raw: MOCK_RAW_TOKEN, hash: MOCK_HASH })),
}));

// ─── Supabase mock ────────────────────────────────────────────────────────────

// WHY mockRpc is separate: tests need to configure return values per-test.
// The factory cannot reference it directly (hoisting issue), so we set
// the resolved value in beforeEach after all consts are live (Fix P0 pattern).
const mockRpc = vi.fn();

// WHY mockFrom is needed: the action does a server-side SELECT on
// support_tickets to resolve p_user_id before calling the request RPC.
const mockFrom = vi.fn();

vi.mock('@/lib/supabase/server', () => ({
  createClient: vi.fn(),
}));

// WHY mock mfa-gate (H42 Layer 1): requestSupportAccessAction calls
// assertAdminMfa(actingAdmin.id) after resolving the acting admin via
// supabase.auth.getUser(). Without this mock the real gate runs createAdminClient
// to query the passkeys table — which is not set up in the unit test environment.
// Gate behaviour is covered by src/lib/admin/__tests__/mfa-gate.test.ts.
// OWASP A07:2021, SOC 2 CC6.1.
vi.mock('@/lib/admin/mfa-gate', () => ({
  assertAdminMfa: vi.fn().mockResolvedValue(undefined),
  AdminMfaRequiredError: class AdminMfaRequiredError extends Error {
    statusCode = 403 as const;
    code = 'ADMIN_MFA_REQUIRED' as const;
    constructor() {
      super('Admin MFA required');
      this.name = 'AdminMfaRequiredError';
    }
  },
}));

import { createClient } from '@/lib/supabase/server';
import { assertAdminMfa, AdminMfaRequiredError } from '@/lib/admin/mfa-gate';
import type { Mock } from 'vitest';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Builds a FormData from a plain record.
 */
function makeFormData(entries: Record<string, string | null | undefined>): FormData {
  const fd = new FormData();
  for (const [key, value] of Object.entries(entries)) {
    if (value != null) fd.append(key, value);
  }
  return fd;
}

const VALID_TICKET_ID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
const VALID_SESSION_ID = 'b2c3d4e5-f6a7-8901-bcde-f12345678901';
const VALID_GRANT_ID = '42';
const VALID_USER_ID = 'ccccdddd-eeee-ffff-aaaa-bbbbccccdddd';
/** Acting admin ID returned by auth.getUser() for assertAdminMfa wiring tests. */
const ACTING_ADMIN_ID = 'aaaabbbb-cccc-dddd-eeee-ffffaaaabbbb';

/** Minimal valid form data for happy-path tests. */
function validFormData(overrides: Record<string, string> = {}): FormData {
  return makeFormData({
    session_id: VALID_SESSION_ID,
    reason: 'User reported cost spike — investigating session tool call pattern.',
    expires_in_hours: '24',
    ...overrides,
  });
}

/**
 * Configure mockRpc to dispatch by RPC name. The default behaviour:
 *   - admin_request_support_access → returns VALID_GRANT_ID
 *   - admin_stash_grant_token      → returns null/no error
 *
 * Tests can override per-call with `.mockImplementationOnce` if needed, or
 * supply per-name overrides via this helper.
 */
function configureRpc(overrides?: {
  request?: { data: unknown; error: unknown };
  stash?: { data: unknown; error: unknown };
}) {
  const requestResult = overrides?.request ?? { data: VALID_GRANT_ID, error: null };
  const stashResult = overrides?.stash ?? { data: null, error: null };
  mockRpc.mockImplementation(async (fnName: string) => {
    if (fnName === 'admin_request_support_access') return requestResult;
    if (fnName === 'admin_stash_grant_token') return stashResult;
    return { data: null, error: null };
  });
}

// ─── Test suites ──────────────────────────────────────────────────────────────

describe('requestSupportAccessAction', () => {
  beforeEach(() => {
    vi.clearAllMocks();

    // WHY rebuild from() chain each test: state would otherwise leak when a
    // test modifies the chain. Default returns the ticket's user_id for any
    // ticket UUID — sufficient for happy-path and error-path tests alike.
    const mockMaybeSingle = vi.fn().mockResolvedValue({
      data: { user_id: VALID_USER_ID },
      error: null,
    });
    const mockEq = vi.fn().mockReturnValue({ maybeSingle: mockMaybeSingle });
    const mockSelect = vi.fn().mockReturnValue({ eq: mockEq });
    mockFrom.mockReturnValue({ select: mockSelect });

    // WHY include auth.getUser: H42 Layer 1 added auth.getUser() calls inside
    // admin actions to resolve the acting admin for the MFA gate (assertAdminMfa).
    // The mock must return a valid admin user so the gate is genuinely exercised.
    (createClient as Mock).mockResolvedValue({
      rpc: mockRpc,
      from: mockFrom,
      auth: {
        getUser: vi.fn().mockResolvedValue({
          data: { user: { id: ACTING_ADMIN_ID, email: 'admin@styrby.test' } },
        }),
      },
    });

    // Default: both RPCs succeed.
    configureRpc();
  });

  // ── (a) Zod validation ─────────────────────────────────────────────────────

  it('(a) rejects invalid session_id UUID', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(
      VALID_TICKET_ID,
      makeFormData({
        session_id: 'not-a-uuid',
        reason: 'Valid reason with enough characters.',
        expires_in_hours: '24',
      })
    );

    expect(result).toMatchObject({ ok: false, field: 'session_id' });
    expect(mockRpc).not.toHaveBeenCalled();
  });

  it('(a) rejects reason shorter than 10 chars', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(
      VALID_TICKET_ID,
      makeFormData({
        session_id: VALID_SESSION_ID,
        reason: 'Short',
        expires_in_hours: '24',
      })
    );

    expect(result).toMatchObject({ ok: false, field: 'reason' });
    expect(mockRpc).not.toHaveBeenCalled();
  });

  it('(h) accepts reason of exactly 10 chars', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(
        VALID_TICKET_ID,
        makeFormData({
          session_id: VALID_SESSION_ID,
          reason: '1234567890',
          expires_in_hours: '24',
        })
      )
    ).rejects.toThrow(/NEXT_REDIRECT/);

    // Both RPCs must have been called.
    const calls = mockRpc.mock.calls.map((c) => c[0]);
    expect(calls).toContain('admin_request_support_access');
    expect(calls).toContain('admin_stash_grant_token');
  });

  it('(h) rejects reason longer than 500 chars', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(
      VALID_TICKET_ID,
      makeFormData({
        session_id: VALID_SESSION_ID,
        reason: 'A'.repeat(501),
        expires_in_hours: '24',
      })
    );

    expect(result).toMatchObject({ ok: false, field: 'reason' });
    expect(mockRpc).not.toHaveBeenCalled();
  });

  it('(g) rejects expires_in_hours = 0', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(
      VALID_TICKET_ID,
      makeFormData({
        session_id: VALID_SESSION_ID,
        reason: 'Valid reason with enough characters.',
        expires_in_hours: '0',
      })
    );

    expect(result).toMatchObject({ ok: false, field: 'expires_in_hours' });
    expect(mockRpc).not.toHaveBeenCalled();
  });

  it('(g) rejects expires_in_hours = 169', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(
      VALID_TICKET_ID,
      makeFormData({
        session_id: VALID_SESSION_ID,
        reason: 'Valid reason with enough characters.',
        expires_in_hours: '169',
      })
    );

    expect(result).toMatchObject({ ok: false, field: 'expires_in_hours' });
    expect(mockRpc).not.toHaveBeenCalled();
  });

  it('(g) accepts expires_in_hours = 1 (boundary)', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData({ expires_in_hours: '1' }))
    ).rejects.toThrow(/NEXT_REDIRECT/);
  });

  it('(g) accepts expires_in_hours = 168 (boundary)', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData({ expires_in_hours: '168' }))
    ).rejects.toThrow(/NEXT_REDIRECT/);
  });

  // ── (b) SQLSTATE mapping ───────────────────────────────────────────────────

  it('(b) maps SQLSTATE 42501 to "Not authorized"', async () => {
    configureRpc({ request: { data: null, error: { code: '42501' } } });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toEqual({ ok: false, error: 'Not authorized' });
    // Stash must NOT be called once request fails.
    const stashCalls = mockRpc.mock.calls.filter((c) => c[0] === 'admin_stash_grant_token');
    expect(stashCalls.length).toBe(0);
  });

  it('(b) maps SQLSTATE 22023 to invalid-session message', async () => {
    configureRpc({
      request: {
        data: null,
        error: { code: '22023', message: 'session does not belong to ticket user' },
      },
    });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toMatchObject({ ok: false });
    expect((result as { ok: false; error: string }).error).toContain('Invalid session');
  });

  it('(b) maps SQLSTATE 23514 to "Reason is required"', async () => {
    configureRpc({ request: { data: null, error: { code: '23514' } } });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toEqual({ ok: false, error: 'Reason is required' });
  });

  it('(b) maps unknown SQLSTATE to "Internal error" and captures Sentry', async () => {
    configureRpc({
      request: { data: null, error: { code: 'P0001', message: 'unexpected rpc error' } },
    });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toMatchObject({ ok: false, error: 'Internal error — check Sentry' });
    expect(mockSentryCaptureException).toHaveBeenCalled();
    const [, sentryCtx] = mockSentryCaptureException.mock.calls[0];
    expect(sentryCtx.tags.admin_action).toBe('request_support_access');
  });

  // ── (c) Happy path ─────────────────────────────────────────────────────────

  it('(c) calls request RPC with correct args (p_user_id from ticket; no p_ip / p_ua)', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData())
    ).rejects.toThrow(/NEXT_REDIRECT/);

    const requestCall = mockRpc.mock.calls.find(
      (c) => c[0] === 'admin_request_support_access'
    );
    expect(requestCall).toBeDefined();
    expect(requestCall![1]).toEqual({
      p_ticket_id: VALID_TICKET_ID,
      p_user_id: VALID_USER_ID,
      p_session_id: VALID_SESSION_ID,
      p_reason: 'User reported cost spike — investigating session tool call pattern.',
      p_expires_in_hours: 24,
      p_token_hash: MOCK_HASH,
    });
    const requestArgs = requestCall![1] as Record<string, unknown>;
    expect(requestArgs).not.toHaveProperty('p_ip');
    expect(requestArgs).not.toHaveProperty('p_ua');
  });

  it('(c) does NOT touch cookies — replaces the prior non-HttpOnly cookie channel (SEC-ADV-001)', async () => {
    // The action's import list no longer pulls `cookies` from next/headers.
    // We assert this indirectly: if cookies were called, our next/headers
    // mock (which exposes only `headers`) would throw on the missing export.
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData())
    ).rejects.toThrow(/NEXT_REDIRECT/);

    // No assertion needed beyond the redirect — the test passes only if the
    // action completed without invoking the (non-existent) cookies() helper.
  });

  it('(c) redirects to success page with grant ID', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData())
    ).rejects.toThrow(/NEXT_REDIRECT/);

    expect(mockRedirect).toHaveBeenCalledWith(
      `/dashboard/admin/support/${VALID_TICKET_ID}/request-access/success?grant=${VALID_GRANT_ID}`
    );
    expect(mockRevalidatePath).toHaveBeenCalledWith(
      `/dashboard/admin/support/${VALID_TICKET_ID}`
    );
  });

  // ── (d) Cross-user session rejection via request RPC ───────────────────────

  it('(d) returns invalid-session error when request RPC raises 22023 (cross-user session)', async () => {
    configureRpc({
      request: {
        data: null,
        error: { code: '22023', message: 'session user_id does not match ticket user_id' },
      },
    });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toMatchObject({ ok: false });
    expect((result as { ok: false; error: string }).error).toContain('Invalid session');
    expect(mockRedirect).not.toHaveBeenCalled();
  });

  // ── (e) Ticket ID binding integrity ───────────────────────────────────────

  it('(e) passes the trustedTicketId from .bind() to the request RPC', async () => {
    const ANOTHER_TICKET = 'ffffffff-1111-2222-3333-444444444444';
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(ANOTHER_TICKET, validFormData())
    ).rejects.toThrow(/NEXT_REDIRECT/);

    const requestCall = mockRpc.mock.calls.find(
      (c) => c[0] === 'admin_request_support_access'
    );
    expect(requestCall![1]).toMatchObject({
      p_ticket_id: ANOTHER_TICKET,
      p_user_id: VALID_USER_ID,
    });
  });

  // ── (f) Raw token leakage prevention ──────────────────────────────────────

  it('(f) does not include raw token in Sentry extras on request-RPC error', async () => {
    configureRpc({
      request: { data: null, error: { code: 'P0001', message: 'unexpected' } },
    });
    const { requestSupportAccessAction } = await import('../actions');

    await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    const sentryExtra = mockSentryCaptureException.mock.calls[0]?.[1]?.extra ?? {};
    expect(JSON.stringify(sentryExtra)).not.toContain(MOCK_RAW_TOKEN);
  });

  it('(f) does not include raw token in the action return value on error', async () => {
    configureRpc({ request: { data: null, error: { code: '42501' } } });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(JSON.stringify(result)).not.toContain(MOCK_RAW_TOKEN);
  });

  // ── (i) Stash RPC failure path ─────────────────────────────────────────────

  it('(i) surfaces a user-facing error and skips redirect when stash RPC fails', async () => {
    configureRpc({
      stash: {
        data: null,
        error: { code: 'P0001', message: 'unique violation or auth error' },
      },
    });
    const { requestSupportAccessAction } = await import('../actions');

    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toMatchObject({ ok: false });
    expect((result as { ok: false; error: string }).error).toContain('Token could not be stored');
    // Redirect must not have been called.
    expect(mockRedirect).not.toHaveBeenCalled();
    // Sentry must capture the stash failure.
    expect(mockSentryCaptureException).toHaveBeenCalled();
    const [, sentryCtx] = mockSentryCaptureException.mock.calls[0];
    expect(sentryCtx.tags.admin_action).toBe('stash_grant_token');
    // Raw token must never reach Sentry — even on stash failure.
    expect(JSON.stringify(sentryCtx.extra ?? {})).not.toContain(MOCK_RAW_TOKEN);
  });

  // ── (j) Stash RPC arg fidelity ────────────────────────────────────────────

  it('(j) calls stash RPC with the grantId from request RPC and the raw token from generateSupportToken', async () => {
    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData())
    ).rejects.toThrow(/NEXT_REDIRECT/);

    const stashCall = mockRpc.mock.calls.find((c) => c[0] === 'admin_stash_grant_token');
    expect(stashCall).toBeDefined();
    expect(stashCall![1]).toEqual({
      p_grant_id: VALID_GRANT_ID,
      p_raw_token: MOCK_RAW_TOKEN,
    });
  });

  it('(j) the request RPC is called BEFORE the stash RPC (order matters)', async () => {
    const callOrder: string[] = [];
    mockRpc.mockImplementation(async (fnName: string) => {
      callOrder.push(fnName);
      if (fnName === 'admin_request_support_access') {
        return { data: VALID_GRANT_ID, error: null };
      }
      if (fnName === 'admin_stash_grant_token') {
        return { data: null, error: null };
      }
      return { data: null, error: null };
    });

    const { requestSupportAccessAction } = await import('../actions');

    await expect(
      requestSupportAccessAction(VALID_TICKET_ID, validFormData())
    ).rejects.toThrow(/NEXT_REDIRECT/);

    expect(callOrder).toEqual([
      'admin_request_support_access',
      'admin_stash_grant_token',
    ]);
  });

  // ── (MFA gate) H42 Layer 1 wiring proof ──────────────────────────────────────

  // WHY: proves requestSupportAccessAction calls assertAdminMfa before running any
  // RPC. If the gate throws AdminMfaRequiredError, the action must short-circuit
  // and return { ok: false, error: 'ADMIN_MFA_REQUIRED' } without calling any RPC.
  // OWASP A07:2021, SOC 2 CC6.1.
  it('(MFA gate) returns ADMIN_MFA_REQUIRED and skips both RPCs when assertAdminMfa throws', async () => {
    (assertAdminMfa as Mock).mockRejectedValueOnce(new AdminMfaRequiredError());

    const { requestSupportAccessAction } = await import('../actions');
    const result = await requestSupportAccessAction(VALID_TICKET_ID, validFormData());

    expect(result).toEqual({ ok: false, error: 'ADMIN_MFA_REQUIRED' });
    expect(assertAdminMfa).toHaveBeenCalledWith(ACTING_ADMIN_ID);
    expect(mockRpc).not.toHaveBeenCalled();
  });
});
