-- Rollback for 085: GRANT EXECUTE TO PUBLIC for the 69 functions tightened.
-- WARNING: rolling back re-exposes these functions to the anon role.
-- Only use if a verified pre-auth call path is discovered.
GRANT EXECUTE ON FUNCTION public.accept_team_invitation(p_invitation_token text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.accept_team_invitation(p_invitation_id uuid, p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.acquire_team_invite_lock(team_lock_key bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_consume_support_access(p_token_hash text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_idempotency_check(p_actor_id uuid, p_action text, p_target_user_id uuid, p_reason text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_idempotency_check_with_event(p_actor_id uuid, p_action text, p_target_user_id uuid, p_reason text, p_event_id text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_issue_credit(p_target_user_id uuid, p_amount_cents bigint, p_currency text, p_reason text, p_expires_at timestamp with time zone) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_issue_refund(p_target_user_id uuid, p_amount_cents bigint, p_currency text, p_reason text, p_polar_event_id text, p_polar_refund_id text, p_polar_subscription_id text, p_polar_response_json jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_override_tier(p_target_user_id uuid, p_new_tier text, p_expires_at timestamp with time zone, p_reason text, p_ip inet, p_ua text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_pickup_grant_token(p_grant_id bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_record_password_reset(p_target_user_id uuid, p_reason text, p_ip inet, p_ua text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_request_support_access(p_ticket_id uuid, p_user_id uuid, p_session_id uuid, p_reason text, p_expires_in_hours integer, p_token_hash text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_revoke_credit(p_credit_id bigint, p_reason text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_send_churn_save_offer(p_target_user_id uuid, p_kind churn_offer_kind, p_reason text, p_polar_discount_code text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_stash_grant_token(p_grant_id bigint, p_raw_token text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_toggle_consent(p_target_user_id uuid, p_purpose consent_purpose, p_grant boolean, p_reason text, p_ip inet, p_ua text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_polar_subscription_with_override_check(p_user_id uuid, p_new_tier text, p_polar_subscription_id text, p_billing_cycle text, p_current_period_end timestamp with time zone, p_polar_event_id text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.audit_trigger_fn() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.auto_generate_webhook_secret() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.auto_sso_enroll(p_user_id uuid, p_team_id uuid, p_hd_claim text, p_user_email text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_budget_hard_stop(p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_machine_limit() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_team_limit() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.cleanup_old_sent_offline_commands() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.cleanup_support_grant_token_pickup() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.count_team_members_with_seat_lock(p_team_id uuid, p_team_lock_key bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.decrement_team_active_seats() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_expired_sessions() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ensure_single_default_context_template() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.estimate_notification_rate_for_threshold(p_user_id uuid, p_threshold integer, p_days integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.finalize_orphaned_pending_costs() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_dispatch_due_nps_prompts() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_expire_stale_referrals() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_mark_weekly_digest_batch() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.fn_schedule_nps_prompts() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_webhook_secret() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_accounts_pending_hard_delete() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_daily_spending(p_user_id uuid, p_days integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_notification_suppression_rate(p_user_id uuid, p_days integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_spending_by_agent(p_user_id uuid, p_days integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_team_cost_by_agent(p_team_id uuid, p_start_date date, p_end_date date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_team_cost_summary_v2(p_team_id uuid, p_start_date date, p_end_date date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_team_members(p_team_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_team_sso_policy(p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_user_spending(p_user_id uuid, p_period text, p_agent_type agent_type) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_user_teams() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_new_team() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_new_user_context_templates() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_team_active_seats() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.insert_session_message(p_session_id uuid, p_message_type text, p_content_encrypted text, p_encryption_nonce text, p_parent_message_id uuid, p_permission_granted boolean, p_metadata jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.invoke_summary_generation() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_site_admin(p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_team_member(_team_id uuid, _user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.lookup_api_key(p_prefix text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.notify_push_for_message() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.queue_webhook_delivery(p_user_id uuid, p_event webhook_event, p_payload jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.refresh_daily_cost_summary() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.revoke_api_key(p_key_id uuid, p_reason text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_users_by_email_for_admin(p_query text, p_limit integer, p_offset integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.seed_default_context_templates(p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_agent_context_memory_updated_at() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_agent_session_groups_updated_at() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.trigger_budget_exceeded_webhook(p_user_id uuid, p_alert_id uuid, p_alert_name text, p_current_spend numeric, p_threshold numeric, p_period text, p_action text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.trigger_permission_requested_webhook() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.trigger_session_completed_webhook() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.trigger_session_started_webhook() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_api_key_usage(p_key_id uuid, p_ip_address inet) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_session_cost_on_finalize() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_session_costs() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_session_message_count() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_webhook_delivery_stats() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.user_accept_churn_save_offer(p_offer_id bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.user_approve_support_access(p_grant_id bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.user_revoke_support_access(p_grant_id bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.verify_admin_audit_chain() TO PUBLIC;
