-- ============================================================================
-- Migration 015: Named Session Checkpoints
-- ============================================================================
-- Purpose: Add session_checkpoints table for storing user-defined branch
-- points in the session message timeline.
--
-- WHY: Inspired by Gemini CLI's `/resume save [name]` command. Users conducting
-- long AI coding sessions want to mark "known good" states before experimenting
-- so they can restore the context if things go wrong.
--
-- Each checkpoint records:
--   - The session it belongs to (FK → sessions.id)
--   - A user-provided name (unique within the session)
--   - An optional description
--   - The message sequence number at the time of creation
--   - A lightweight context snapshot (token count + file count)
--
-- RLS: Users can only read, insert, update, and delete their own checkpoints
-- (enforced via user_id = auth.uid() policy).
--
-- Unique constraint on (session_id, name) prevents duplicate names per session,
-- matching the CLI's expectation that names are human-readable identifiers.
-- ============================================================================

-- ============================================================================
-- Table: session_checkpoints
-- ============================================================================

CREATE TABLE IF NOT EXISTS session_checkpoints (
  -- Primary key: UUID v4, generated by client or server
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Owning session (CASCADE delete so checkpoints are removed with sessions)
  session_id    UUID NOT NULL
                REFERENCES sessions(id)
                ON DELETE CASCADE,

  -- Owning user (belt-and-suspenders alongside RLS; required for fast index)
  user_id       UUID NOT NULL
                REFERENCES auth.users(id)
                ON DELETE CASCADE,

  -- Human-readable name (unique within a session)
  -- Allowed characters: letters, numbers, spaces, hyphens, underscores, dots
  name          TEXT NOT NULL
                CONSTRAINT session_checkpoints_name_length CHECK (
                  char_length(name) BETWEEN 1 AND 80
                )
                CONSTRAINT session_checkpoints_name_chars CHECK (
                  name ~ '^[a-zA-Z0-9 \-_.]+$'
                ),

  -- Optional longer description
  description   TEXT,

  -- The sequence_number of the last message at checkpoint creation time.
  -- Used to reconstruct "show messages 1 through N" for a restore operation.
  message_sequence_number  INTEGER NOT NULL DEFAULT 0
                           CONSTRAINT session_checkpoints_seq_non_negative CHECK (
                             message_sequence_number >= 0
                           ),

  -- Lightweight context window snapshot at checkpoint time.
  -- Shape: { "totalTokens": number, "fileCount": number }
  context_snapshot  JSONB NOT NULL DEFAULT '{}',

  -- Timestamps
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Unique Constraint
-- ============================================================================

-- Names must be unique within a session so users can reference them by name.
-- The CLI and Web/Mobile UIs surface a friendly error when this is violated.
ALTER TABLE session_checkpoints
  DROP CONSTRAINT IF EXISTS session_checkpoints_session_name_unique;

ALTER TABLE session_checkpoints
  ADD CONSTRAINT session_checkpoints_session_name_unique
  UNIQUE (session_id, name);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Primary access pattern: list all checkpoints for a session
CREATE INDEX IF NOT EXISTS idx_session_checkpoints_session_id
  ON session_checkpoints (session_id, created_at DESC);

-- Secondary access pattern: list all checkpoints for a user (dashboard view)
CREATE INDEX IF NOT EXISTS idx_session_checkpoints_user_id
  ON session_checkpoints (user_id, created_at DESC);

-- ============================================================================
-- Updated-at trigger
-- ============================================================================

-- WHY: updated_at is maintained via trigger rather than application code so
-- it is always accurate even for direct SQL mutations (admin, migrations).
CREATE OR REPLACE TRIGGER session_checkpoints_updated_at
  BEFORE UPDATE ON session_checkpoints
  FOR EACH ROW
  EXECUTE FUNCTION moddatetime(updated_at);

-- ============================================================================
-- Row-Level Security
-- ============================================================================

ALTER TABLE session_checkpoints ENABLE ROW LEVEL SECURITY;

-- Users can only see their own checkpoints
CREATE POLICY "session_checkpoints_select_own"
  ON session_checkpoints
  FOR SELECT
  USING (user_id = (SELECT auth.uid()));

-- Users can only insert checkpoints owned by themselves
CREATE POLICY "session_checkpoints_insert_own"
  ON session_checkpoints
  FOR INSERT
  WITH CHECK (user_id = (SELECT auth.uid()));

-- Users can update their own checkpoints (e.g. rename or update description)
CREATE POLICY "session_checkpoints_update_own"
  ON session_checkpoints
  FOR UPDATE
  USING (user_id = (SELECT auth.uid()))
  WITH CHECK (user_id = (SELECT auth.uid()));

-- Users can delete their own checkpoints
CREATE POLICY "session_checkpoints_delete_own"
  ON session_checkpoints
  FOR DELETE
  USING (user_id = (SELECT auth.uid()));

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE session_checkpoints IS
  'Named branch points in a session timeline. '
  'Users save checkpoints to mark known-good states before experimenting. '
  'Checkpoints are unique by name within each session.';

COMMENT ON COLUMN session_checkpoints.name IS
  'User-provided label (1–80 chars). Must be unique within the parent session.';

COMMENT ON COLUMN session_checkpoints.message_sequence_number IS
  'The sequence_number of the most recent session_messages row at checkpoint '
  'creation time. Used by restore operations to filter messages to N.';

COMMENT ON COLUMN session_checkpoints.context_snapshot IS
  'Lightweight snapshot of the agent context window at checkpoint time. '
  'Shape: { "totalTokens": number, "fileCount": number }.';
