-- ============================================================================
-- MIGRATION 028: Lamport Clock + Offline Queue Audit Actions
-- ============================================================================
-- Phase 1.6.3b — Offline Queue Hardening Follow-Up
--
-- Changes:
--   1. Add `lamport_clock` column to session_messages for deterministic
--      conflict resolution when two messages share the same created_at
--      (concurrent sends from phone and terminal).
--   2. Add `idempotency_key` column to session_messages so the server can
--      detect and reject duplicate inserts from chaos-recovery retries.
--   3. Extend audit_action enum with offline-queue-specific actions:
--      'offline_queue_cleared', 'offline_queue_partial_clear'
--
-- WHY lamport_clock: Wall-clock timestamps cannot distinguish simultaneous
-- sends. A Lamport clock is a monotonic logical counter that advances on
-- every local send AND on receipt of any remote message with a higher
-- counter value. When two messages share the same `created_at`, ordering by
-- (lamport_clock, origin_id) is deterministic across all replays.
--
-- WHY idempotency_key: If the app is killed between the network call and
-- `markSent`, the chaos-recovery path will retry the send. The server must
-- recognize the retry as a duplicate and return a 200 without inserting a
-- second row. The key is a UUID generated BEFORE the first send attempt so
-- retries carry the same key.
--
-- WHY audit_action additions: Per the enterprise-grade mandate, every
-- user-initiated offline queue clear must produce an immutable audit_log row.
-- The existing enum does not have a suitable action type.
-- ============================================================================


-- ============================================================================
-- STEP 1: Extend audit_action enum
-- ============================================================================
-- WHY ALTER TYPE ... ADD VALUE: Postgres enums are safe to extend with new
-- values in a migration without rebuilding the table. The new values are
-- appended and do not affect existing rows or indexes.

ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'offline_queue_cleared';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'offline_queue_partial_clear';


-- ============================================================================
-- STEP 2: Add lamport_clock to session_messages
-- ============================================================================

ALTER TABLE session_messages
  ADD COLUMN IF NOT EXISTS lamport_clock BIGINT NOT NULL DEFAULT 0;

COMMENT ON COLUMN session_messages.lamport_clock IS
  'Lamport logical clock value at the time of send. '
  'Advances on every local send AND when a remote message with a higher '
  'lamport_clock is received. Used to break created_at ties deterministically '
  'when phone and terminal send concurrently. Ordering: (created_at, lamport_clock, id).';

-- Index for the conflict-resolution sort: same-second messages ordered by
-- (lamport_clock, id) within a session.
CREATE INDEX IF NOT EXISTS idx_messages_lamport_ordering
  ON session_messages(session_id, created_at, lamport_clock, id);


-- ============================================================================
-- STEP 3: Add idempotency_key to session_messages
-- ============================================================================
-- WHY nullable default NULL: Existing rows have no idempotency key (they were
-- inserted before this migration). New inserts MUST supply one. We enforce
-- this at the application layer; a NOT NULL constraint would break old clients
-- that have not yet updated.

ALTER TABLE session_messages
  ADD COLUMN IF NOT EXISTS idempotency_key UUID;

COMMENT ON COLUMN session_messages.idempotency_key IS
  'UUID generated by the client BEFORE the first send attempt. '
  'Retries after a crash carry the same key, allowing the server to return '
  '200 without inserting a duplicate row. NULL on legacy rows created before '
  'migration 028.';

-- Unique partial index: enforce no-duplicate-insert on new rows that carry a key.
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_idempotency_key
  ON session_messages(idempotency_key)
  WHERE idempotency_key IS NOT NULL;


-- ============================================================================
-- STEP 4: RLS — no new policies needed
-- ============================================================================
-- Both new columns are covered by existing session_messages RLS policies
-- (users can only SELECT/INSERT their own session's messages). The
-- idempotency_key and lamport_clock columns carry no additional PII.
