-- Migration 063: Create cloud_tasks table
--
-- WHY this table is needed: The Cloud Task Monitoring feature (Power tier) lets
-- users submit long-running agent jobs from the CLI and monitor them from the
-- mobile app and web dashboard. The CLI inserts rows as tasks progress through
-- queued → running → completed/failed/cancelled. The mobile and web components
-- subscribe via Supabase Realtime.
--
-- This table was referenced in the codebase (web CloudTasksPanel, mobile
-- CloudTasks, shared types.ts CloudTask interface) since Phase 7 Batch 2
-- but was never accompanied by a CREATE TABLE migration. The H26 drift audit
-- surfaced the gap.
--
-- Columns inferred from the following code references:
--   - packages/styrby-web/src/components/cloud-tasks.tsx  (SELECT *, UPDATE)
--   - packages/styrby-mobile/src/components/CloudTasks.tsx (SELECT *, UPDATE)
--   - packages/styrby-shared/src/types.ts (CloudTask interface)
--
-- WHY agent_type is TEXT not the agent_type ENUM: The existing enum (migration
-- 001) only contains 'claude', 'codex', 'gemini'. Cloud tasks support all 11
-- agents (including opencode, aider, goose, amp, crush, kilo, kiro, droid).
-- Rather than ALTER the shared enum here (which would touch live tables with
-- active RLS policies), we use a TEXT column with a CHECK constraint. A
-- separate migration can normalize the enum when all tables are ready.
--
-- ROLLBACK: DROP TABLE public.cloud_tasks;
--
-- Risk class: SAFE — net-new table, no existing rows, no ALTER on live table.
-- ============================================================================

-- ============================================================================
-- §1. Status type
-- ============================================================================

-- WHY DO block: CREATE TYPE IF NOT EXISTS doesn't exist in PostgreSQL.
-- The DO block is idempotent — it skips if the type already exists.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cloud_task_status') THEN
    CREATE TYPE public.cloud_task_status AS ENUM (
      'queued',     -- Submitted, waiting for an available agent slot
      'running',    -- Agent is actively executing the task
      'completed',  -- Task finished successfully with a result
      'failed',     -- Task ended in an error
      'cancelled'   -- User cancelled the task before completion
    );
  END IF;
END;
$$;

COMMENT ON TYPE public.cloud_task_status IS
  'Lifecycle states for an asynchronous cloud agent task (Phase 7.17).';

-- ============================================================================
-- §2. Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.cloud_tasks (
  -- UUID primary key, generated by the inserting caller (CLI).
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- FK to auth.users — the owner of this task.
  -- WHY 'user_id': used in both SELECT and Realtime filter
  -- (filter: `user_id=eq.${userId}`), and in account deletion.
  user_id               UUID        NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,

  -- Optional FK to sessions — links a cloud task to its originating session.
  -- NULL for standalone tasks submitted without an active session context.
  session_id            UUID        REFERENCES public.sessions (id) ON DELETE SET NULL,

  -- Agent that will execute this task.
  -- TEXT + CHECK (not the shared agent_type enum) to support all 11 agents.
  -- See migration header for rationale.
  agent_type            TEXT        NOT NULL
    CHECK (agent_type IN (
      'claude', 'codex', 'gemini', 'opencode', 'aider',
      'goose', 'amp', 'crush', 'kilo', 'kiro', 'droid'
    )),

  -- Current lifecycle state.
  status                public.cloud_task_status NOT NULL DEFAULT 'queued',

  -- User-supplied instruction or prompt.
  -- WHY plaintext: stored for display in the monitoring UI. The CLI may
  -- separately encrypt the full execution payload, but the prompt label
  -- is intentionally human-readable in the dashboard.
  prompt                TEXT        NOT NULL,

  -- Terminal state outputs (mutually exclusive in normal flow).
  result                TEXT,       -- Populated when status = 'completed'
  error_message         TEXT,       -- Populated when status = 'failed'

  -- Timestamps
  -- WHY started_at not created_at: matches the CloudTask interface field name
  -- and the intent — the CLI sets this when the task is submitted.
  started_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at          TIMESTAMPTZ,            -- Set when status reaches any terminal state

  -- Optional duration estimate (milliseconds).
  -- WHY: Drives the progress bar in the mobile and web monitoring UIs.
  estimated_duration_ms INTEGER     CHECK (estimated_duration_ms IS NULL OR estimated_duration_ms > 0),

  -- Total cost in USD incurred by this task (set by CLI on completion).
  cost_usd              NUMERIC(12, 6),

  -- Freeform display metadata (project path, git branch, model name).
  -- Stored as JSONB for forward-compatibility without schema changes.
  metadata              JSONB,

  -- Soft-audit: when the row was last modified.
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.cloud_tasks IS
  'Asynchronous cloud agent tasks submitted via CLI, monitored from mobile/web (Power tier, Phase 7.17).';

COMMENT ON COLUMN public.cloud_tasks.agent_type IS
  'TEXT (not enum) to support all 11 agents. See migration 063 header for normalization plan.';
COMMENT ON COLUMN public.cloud_tasks.metadata IS
  'JSONB: { projectPath?, gitBranch?, model? }. Rendered in monitoring UI task cards.';

-- ============================================================================
-- §3. Indexes
-- ============================================================================

-- Primary access pattern: list this user's tasks ordered by recency.
-- WHY DESC: all queries order by started_at DESC; a DESC index avoids a sort.
CREATE INDEX IF NOT EXISTS idx_cloud_tasks_user_started
  ON public.cloud_tasks (user_id, started_at DESC);

-- Partial index: active tasks only (queued + running).
-- WHY: Dashboard badge counts and realtime update targeting hit active tasks
-- far more than terminal tasks; this index is tiny and fast.
CREATE INDEX IF NOT EXISTS idx_cloud_tasks_active
  ON public.cloud_tasks (user_id, status)
  WHERE status IN ('queued', 'running');

-- Lookup by parent session (for "tasks spawned from this session" view).
CREATE INDEX IF NOT EXISTS idx_cloud_tasks_session_id
  ON public.cloud_tasks (session_id)
  WHERE session_id IS NOT NULL;

-- ============================================================================
-- §4. updated_at trigger
-- ============================================================================

-- Reuse the update_updated_at() trigger function established in migration 001.
CREATE OR REPLACE TRIGGER set_cloud_tasks_updated_at
  BEFORE UPDATE ON public.cloud_tasks
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- §5. Row-Level Security
-- ============================================================================

ALTER TABLE public.cloud_tasks ENABLE ROW LEVEL SECURITY;

-- Policy: users can SELECT their own tasks only.
-- Realtime subscription filter (user_id=eq.${userId}) provides defense-in-depth,
-- but RLS is the authoritative enforcement layer.
CREATE POLICY "cloud_tasks: owner select"
  ON public.cloud_tasks
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- Policy: users can INSERT their own tasks.
-- WHY: In the current design, tasks are inserted by the CLI using the user's
-- JWT (anon key + user session). Future headless insertion uses service_role.
CREATE POLICY "cloud_tasks: owner insert"
  ON public.cloud_tasks
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- Policy: users can UPDATE their own tasks (cancel: set status = 'cancelled').
-- WHY: The cancel button in web + mobile sets status directly via Supabase client.
CREATE POLICY "cloud_tasks: owner update"
  ON public.cloud_tasks
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- Policy: users can DELETE their own tasks.
CREATE POLICY "cloud_tasks: owner delete"
  ON public.cloud_tasks
  FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- ============================================================================
-- §6. Grant
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.cloud_tasks
  TO authenticated;

-- service_role needed for:
--  (a) CLI inserts/updates using a server-side service key
--  (b) Realtime change publication (postgres_changes requires table-level access)
GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.cloud_tasks
  TO service_role;

-- ============================================================================
-- §7. Realtime publication
-- ============================================================================

-- WHY: Realtime postgres_changes subscriptions require the table to be in the
-- supabase_realtime publication. Without this, the .on('postgres_changes', ...)
-- subscriptions in CloudTasksPanel and CloudTasks components never fire.
ALTER PUBLICATION supabase_realtime ADD TABLE public.cloud_tasks;
