/**
 * Cost Types and Utilities
 *
 * Shared types and formatting utilities for cost data display.
 * Used by the cost dashboard components (DailyCostChart, CostsByAgentChart,
 * CostTable, CostSummaryCard).
 *
 * Data fetching is handled inline in the costs page server component
 * and in the mobile app's useCosts hook.
 *
 * @module lib/costs
 */

// ============================================================================
// Types
// ============================================================================

/**
 * Agent types supported by Styrby.
 *
 * WHY: Matches the agent_type column in cost_records table.
 */
export type AgentType = 'claude' | 'codex' | 'gemini' | 'opencode' | 'aider';

/**
 * Cost summary for a time period.
 *
 * Represents aggregated token counts and cost for a dashboard card.
 */
export interface CostSummary {
  /** Total cost in USD */
  totalCost: number;
  /** Total input tokens */
  inputTokens: number;
  /** Total output tokens */
  outputTokens: number;
  /** Total cache read tokens */
  cacheReadTokens: number;
  /** Total cache write tokens */
  cacheWriteTokens: number;
  /** Number of API requests */
  requestCount: number;
}

/**
 * Cost breakdown by agent type.
 *
 * Used for the agent breakdown chart on the dashboard.
 */
export interface AgentCostBreakdown {
  /** Agent identifier */
  agent: AgentType;
  /** Total cost for this agent in USD */
  cost: number;
  /** Input tokens consumed by this agent */
  inputTokens: number;
  /** Output tokens generated by this agent */
  outputTokens: number;
  /** Number of requests made to this agent */
  requestCount: number;
  /** Percentage of total cost (0-100) */
  percentage: number;
}

/**
 * Cost breakdown by model.
 *
 * Used for the detailed cost table on the dashboard.
 */
export interface ModelCostBreakdown {
  /** Model identifier (e.g., 'claude-sonnet-4-20250514') */
  model: string;
  /** Which agent uses this model */
  agent: AgentType;
  /** Total cost for this model in USD */
  cost: number;
  /** Input tokens consumed */
  inputTokens: number;
  /** Output tokens generated */
  outputTokens: number;
  /** Number of requests */
  requestCount: number;
}

/**
 * Daily cost data point for time-series charts.
 *
 * Includes total and per-agent breakdown for stacked charts.
 */
export interface DailyCostDataPoint {
  /** Date string in YYYY-MM-DD format */
  date: string;
  /** Total cost for this day */
  total: number;
  /** Cost from Claude Code */
  claude: number;
  /** Cost from Codex */
  codex: number;
  /** Cost from Gemini CLI */
  gemini: number;
  /** Cost from OpenCode */
  opencode: number;
  /** Cost from Aider */
  aider: number;
}

// ============================================================================
// Formatting Utilities
// ============================================================================

/**
 * Format cost as USD currency string.
 *
 * @param cost - Cost value in USD
 * @param decimals - Number of decimal places (default: 2)
 * @returns Formatted currency string like "$12.50"
 *
 * @example
 * formatCost(12.5)     // "$12.50"
 * formatCost(0.0042, 4) // "$0.0042"
 */
export function formatCost(cost: number, decimals: number = 2): string {
  return `$${cost.toFixed(decimals)}`;
}

/**
 * Format token count with K/M suffix for readability.
 *
 * @param tokens - Number of tokens
 * @returns Formatted token string like "1.5K" or "2.3M"
 *
 * @example
 * formatTokens(500)      // "500"
 * formatTokens(1500)     // "1.5K"
 * formatTokens(1500000)  // "1.5M"
 */
export function formatTokens(tokens: number): string {
  if (tokens >= 1_000_000) {
    return `${(tokens / 1_000_000).toFixed(1)}M`;
  }
  if (tokens >= 1_000) {
    return `${(tokens / 1_000).toFixed(1)}K`;
  }
  return tokens.toString();
}

// ============================================================================
// Color Utilities
// ============================================================================

/**
 * Get Tailwind CSS background color class for an agent.
 *
 * @param agent - Agent type
 * @returns Tailwind CSS class like "bg-orange-500"
 *
 * @example
 * <div className={getAgentColor('claude')} /> // bg-orange-500
 */
export function getAgentColor(agent: AgentType): string {
  switch (agent) {
    case 'claude':
      return 'bg-orange-500';
    case 'codex':
      return 'bg-green-500';
    case 'gemini':
      return 'bg-blue-500';
    case 'opencode':
      return 'bg-purple-500';
    case 'aider':
      return 'bg-pink-500';
    default:
      return 'bg-zinc-500';
  }
}
